/*Destruction des tables*/

drop table if exists `admin`;
drop table if exists `professeur`;
drop table if exists `statistique`;
drop table if exists `etudiant`;
drop table if exists `questions`;
drop table if exists `sujets`;
drop table if exists `forumQuestion`;
drop table if exists `forumProposition`;

/* CrÃƒÂ©ation de la table utilisateur*/

create table `etudiant`(
	`id_etudiant` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_etudiant primary key (id_etudiant)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* CrÃƒÂ©ation de la table professeur */

create table `professeur`(
	`id_professeur` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_professeur primary key (id_professeur)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Creation de la table administrateur*/

create table admin(
    id_admin varchar(20) unique,
    password varchar(512),
    constraint pk_admin primary key (id_admin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

/* CrÃƒÂ©ation de la table statistique */

create table `statistique`(
    `id_statistique` int not null,
    `score` float,
    `id_subject` int not null
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*Creation de la table sujets */
create table sujets(
    id int auto_increment primary key,
    domaine varchar(50) not null,
    categorie varchar(50) not null,
    niveau varchar(50) not null
);

/*Creation de la table questions */

create table questions(
	id int auto_increment primary key,
    id_prof int not null,
    id_subject int not null,
    difficulte varchar(50) not null,
    question varchar(500) not null,
    code_reponses varchar(20) not null,
    reponseA varchar(250) not null,
    reponseB varchar(250) not null,
    reponseC varchar(250) not null,
    reponseD varchar(250) not null
);

/*Creation de la table forumQuestion */

create table forumQuestion(
    id int auto_increment primary key,
    question varchar(150) not null,
    id_student int not null,
    answer varchar(150)
);

/*Creation de la table forumProposition */

create table forumProposition(
    id_question int not null,
    proposition varchar(150) not null
);

/*Ajout Student*/
INSERT INTO etudiant(nom, prenom, email, telephone, password, adresse)
VALUES ('Student', 'Student', 'student@student.com', '0101010101', '2286db74888eee2de86d070c65fb9058486ac86e376f499da5fe90dae4d036fa026e7bbcb3a80f34adb7c38b2d3fe5153ed1dc302fd1776fe4b3bd0f9e4386f3', '1 rue des ÃƒÂ©tudiants');

/*Ajout Prof*/
INSERT INTO professeur(nom, prenom, email, telephone, password, adresse)
VALUES ('Prof', 'Prof', 'prof@prof.com', '0202020202', 'b820e9862fa829c9af2ba64a64801097f4542590945b0ea539906e826950c5ba642a9b7d8a432b12f80aad8ad6428f6e7fe035d3e7f5ec5ce5564f5aa0d981ed', '1 rue des professeurs');

/*Ajout admin*/
INSERT INTO admin(id_admin, password)
VALUES ('admin', '5a38afb1a18d408e6cd367f9db91e2ab9bce834cdad3da24183cc174956c20ce35dd39c2bd36aae907111ae3d6ada353f7697a5f1a8fc567aae9e4ca41a9d19d');

/*Remplissage table sujets*/
INSERT INTO sujets(domaine, categorie, niveau)
values ('Mathematiques', 'Nombres', 'Primaire'),
('Mathematiques', 'Grandeurs', 'Primaire'),
('Mathematiques', 'Geometrie', 'Primaire'),
('Mathematiques', 'Statistiques', 'College'),
('Mathematiques', 'Geometrie', 'College'),
('Mathematiques', 'Algebre', 'College'),
('Mathematiques', 'Fonctions', 'Lycee'),
('Mathematiques', 'Suites', 'Lycee'),
('Mathematiques', 'Statistiques', 'Lycee'),
('Mathematiques', 'Algebre', 'Superieur'),
('Mathematiques', 'Analyse', 'Superieur'),
('Mathematiques', 'Probabilites', 'Superieur'),
('Physique', 'Electricite', 'College'),
('Physique', 'Lumiere', 'College'),
('Physique', 'Mecanique', 'College'),
('Physique', 'Electricite', 'Lycee'),
('Physique', 'Ondes', 'Lycee'),
('Physique', 'Optique', 'Lycee'),
('Physique', 'Mecanique', 'Lycee'),
('Physique', 'Mecanique', 'Superieur'),
('Physique', 'Electrocinetique', 'Superieur'),
('Physique', 'Thermodynamique', 'Superieur'),
('Chimie', 'Solutions aqueuses', 'College'),
('Chimie', 'Atomes', 'College'),
('Chimie', 'Atmosphere', 'College'),
('Chimie', '', 'Lycee'),
('Chimie', '', 'Superieur'),
('Biologie', '', 'College'),
('Biologie', '', 'Lycee'),
('Biologie', '', 'Superieur'),
('Geologie', '', 'College'),
('Geologie', '', 'Lycee'),
('Geologie', '', 'Superieur'),
('Informatique', '', 'College'),
('Informatique', 'Programmation', 'Lycee'),
('Informatique', '', 'Lycee'),
('Informatique', 'Programmation', 'Superieur'),
('Informatique', 'Reseaux', 'Superieur'),
('Informatique', 'S. d`exploitation', 'Superieur'),
('Histoire', 'Prehistoire', 'Primaire'),
('Histoire', 'Antiquite', 'Primaire'),
('Histoire', 'Moyen-Age', 'Primaire'),
('Histoire', 'Decouvertes', 'Primaire'),
('Histoire', '', 'Primaire'),
('Histoire', '', 'College'),
('Histoire', '', 'Lycee'),
('Histoire', '', 'Superieur'),
('Geographie', '', 'Primaire'),
('Geographie', '', 'College'),
('Geographie', '', 'Lycee'),
('Geographie', '', 'Superieur'),
('Francais', 'Conjugaison', 'Primaire'),
('Francais', '', 'Primaire'),
('Francais', '', 'College'),
('Francais', '', 'Lycee'),
('Francais', '', 'Superieur'),
('Anglais', '', 'Primaire'),
('Anglais', '', 'College'),
('Anglais', '', 'Lycee'),
('Anglais', '', 'Superieur');


/*Remplissage table questions*/

INSERT INTO questions (id_prof, id_subject, difficulte, question, code_reponses, reponseA, reponseB, reponseC, reponseD)
values (1, 1, 'Facile', '15 + 48 = ?', '010', '54', '63', '36', ''),
(1, 1, 'Facile', '48 - 15 = ?', '100', '23', '32', '33', ''),
(1, 1, 'Facile', '3 x 9 = ?', '001', '18', '36', '27', ''),
(1, 1, 'Facile', '45 / 9 = ?', '01', '4', '5', '', ''),
(1, 1, 'Facile', '15 + 450 = ?', '0100', '455', '465', '15450', '4515'),
(1, 1, 'Facile', '220 - 85 = ?', '1000', '135', '153', '165', '156'),
(1, 1, 'Facile', '7 x 3 = ?', '0010', '28', '14', '21', '35'),
(1, 1, 'Moyen', '56 / 8 = ?', '0001', '5', '6', '9', '7'),
(1, 1, 'Facile', '44 + ... = 78', '010', '25', '34', '38', ''),
(1, 1, 'Moyen', '890 - ... = 148', '001', '756', '648', '742', ''),
(1, 2, 'Facile', '16 cm = ?', '0011', '16 m', '1,6 m', '0,16 m', '160 mm'),
(1, 2, 'Facile', '42 km = ?', '0101', '420 m', '42000 m', '42 cm', '4200000 cm'),
(1, 2, 'Facile', '25 L = ?', '0100', '25 cL', '250 dL', '25000 cL', '2,5 hL'),
(1, 2, 'Facile', '30 mn = ?', '0010', '300 s', '1000 s', '1800 s', '180 s'),
(1, 2, 'Facile', 'Vrai ou Faux : 150 min = 2h30', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 300 ms = 3 s', '01', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 360 s = 6 mn', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 4000 mL = 400 cL', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Facile', 'Comment se nomme une figure ÃƒÂ  3 cÃƒÂ´tÃƒÂ©s ?', '010', 'Un cercle', 'Un triangle', 'Un carrÃƒÂ©', ''),
(1, 3, 'Facile', 'Comment appele-t-on la famille des figures ÃƒÂ  4 cÃƒÂ´tÃƒÂ©s ?', '01', 'Les pentagones', 'Les quadrilatÃƒÂ¨res', '', ''),
(1, 3, 'Facile', 'Quelle figure ne fait pas partie des quadrilatÃƒÂ¨res ?', '0100', 'Le carrÃƒÂ©', 'Le pentagone', 'Le rectangle', 'Le losange'),
(1, 3, 'Moyen', 'Comment calculer le pÃƒÂ©rimÃƒÂ¨tre des carrÃƒÂ©s ?', '110', 'P = c * 4', 'P = (L + l) x 2', 'P = c x c', ''),
(1, 3, 'Moyen', 'Comment calculer le pÃƒÂ©rimÃƒÂ¨tre du cercle ?', '001', 'P = pi x rÃ‚Â²', 'P = pi x r', 'P = pi x 2r', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle droit vaut 90Ã‚Â°', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle obtus est infÃƒÂ©rieur ÃƒÂ  90Ã‚Â°', '01', 'Vrai', 'Faux', '', ''),
(1, 4, 'Moyen', 'Quelle est la moyenne des nombres suivants : 12 18 ?', '0100', '14', '15', '16', '17'),
(1, 4, 'Facile', 'Quelle est la mÃƒÂ©diane des nombres : 13 15 18', '010', '16', '15', '15.33', ''),
(1, 4, 'Facile', 'Quelle est la moyenne des nombres : 7 15 20', '0010', '15', '16', '14', '17'),
(1, 4, 'Facile', 'Quel est le premier quartile ? : 5 10 15 14', '0100', '10', '5', '14', '15'),
(1, 4, 'Facile', '5 boules rouges et 2 boules noires. ProbabilitÃƒÂ© de tirer une boule noire ?', '100', '2/7', '1/7', '5/7', ''),
(1, 4, 'Facile', '3 boules vertes, 2 boules bleues, 1 boule rouge. ProbabilitÃƒÂ© de tirer 2 boules vertes ?', '0100', '2/6', '1/30', '1/11', '1/6'),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant ÃƒÂ  : 15/20', '010', '60%', '75%', '80%', ''),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant ÃƒÂ  : 48/50', '01', '48%', '96%', '', ''),
(1, 4, 'Facile', 'Quelle est la frÃƒÂ©quence correpondant ÃƒÂ  : 4 ÃƒÂ©lÃƒÂ¨ves sur 8', '010', '25%', '50%', '75%', ''),
(1, 4, 'Facile', 'Quelle est la frÃƒÂ©quence correspondant ÃƒÂ  : 8 franÃƒÂ§ais sur 10', '0010', '8%', '40%', '80%', '90%'),
(1, 5, 'Facile', 'Quelle est l`hypothÃƒÂ©nuse d`un triangle rectangle', '01', 'Le cÃƒÂ´tÃƒÂ© le plus court', 'Le cÃƒÂ´tÃƒÂ© le plus long', '', ''),
(1, 5, 'Facile', 'Vrai ou Faux : On peut parler de la mÃƒÂ©diatrice d`une droite', '01', 'Vrai', 'Faux', '', ''),
(1, 5, 'Facile', 'Quelle est la dÃƒÂ©finition de la bissectrice', '010', 'La droite perpendiculaire coupant un segment en deux parts ÃƒÂ©gales', 'La droite coupant un angle en deux parts ÃƒÂ©gales', 'La droite passant par le cente d`un segment', ''),
(1, 5, 'Facile', 'Comment calculer l`aire d`un carrÃƒÂ© ?', '001', 'A = 4 x c', 'A = c + c', 'A = c x c', ''),
(1, 5, 'Facile', 'Comment calculer le volume d`un parallÃƒÂ©lÃƒÂ©pipÃƒÂ¨de rectangle', '010', 'V = l + L + h', 'V = l * L * h', 'V = l * L / h', ''),
(1, 5, 'Facile', 'Comment ÃƒÂ©crire "la droite AB"', '0100', '[AB]', '(AB)', '[AB)', '(AB]'),
(1, 5, 'Facile', 'Quel est le thÃƒÂ©orÃƒÂ¨me de Pythagore ?', '0100', 'ABÃ‚Â² = ACÃ‚Â² = BCÃ‚Â²', 'ABÃ‚Â² + BCÃ‚Â² = ACÃ‚Â²', 'ABÃ‚Â² - BCÃ‚Â² = ACÃ‚Â²', 'BCÃ‚Â² + BAÃ‚Â² = 2AC'),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle isocÃƒÂ¨le ?', '01', 'Un triangle a 3 cÃƒÂ´tÃƒÂ©s ÃƒÂ©gaux', 'Un triangle ÃƒÂ  deux cÃƒÂ´tÃƒÂ©s ÃƒÂ©gaux', '', ''),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle rectangle', '0010', 'Un quadrilatÃƒÂ¨re', 'Un triangle quelconque', 'Un triangle avec un angle droit', 'Un triangle ÃƒÂ  3 cÃƒÂ´tÃƒÂ©s ÃƒÂ©gaux'),
(1, 6, 'Facile', '3x + 15 = 12. x = ?', '0001', '-2', '2', '1', '-1'),
(1, 6, 'Facile', '12 - x = -2. x = ?', '0100', '10', '14', '16', '-10'),
(1, 6, 'Facile', '9x + 9 = 0. x = ?', '1000', '-1', '1', '10', '-10'),
(1, 6, 'Facile', '4x + 5 = x + 2. x = ?', '0010', '1', '3', '-1', '-3'),
(1, 6, 'Facile', '5x + 4 = 2x + 1. x = ?', '0100', '1', '-1', '3', '-3'),
(1, 6, 'Facile', '10x + 5 = 15x. x = ?', '0001', '10', '-1', '3', '1'),
(1, 7, 'Facile', 'Soit f(x) = 3x + 15. Que vaut f(5) ?', '0010', '60', '23', '30', '35'),
(1, 7, 'Facile', 'Soit f(x) = 14x + 12. Quelle est l`ordonnÃƒÂ©e ÃƒÂ  l`origine', '100', '12', '14', '26', ''),
(1, 7, 'Facile', 'Soit f(x) = xÃ‚Â² + 2x + 1. Factoriser', '0100', 'x(x + 2) + 1', '(x + 1)Ã‚Â²', '(x + 1)(x - 1)', '(x - 1)Ã‚Â²'),
(1, 7, 'Facile', 'Soit f(x) = 4xÃ‚Â² + 6x + 15. DÃƒÂ©river', '001', '4x + 6', '2x + 6', '8x + 6', ''),
(1, 7, 'Facile', 'Soit f(x) = 4x. Donner une primitive', '0001', 'x + constante', '4', '2x', '2xÃ‚Â² + constante'),
(1, 7, 'Facile', 'Soit f(x) = 2x + 1. Sur quel intervalle est-elle positive ?', '0010', '[0; +inf[', '[1; +inf[', '[-1; +inf[', '[-1; +inf]'),
(1, 7, 'Facile', 'Soit f(x) = xÃ‚Â². En quelle valeur s`annule-t-elle ?', '01', '1', '0', '', ''),
(1, 7, 'Facile', 'Soit f(x) = -xÃ‚Â² + 3x. Sur quel intervalle est-elle croissante ?', '01', ']-inf; 1.5]', '[1.5; +inf[', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 4. u est-elle une suite gÃƒÂ©omÃƒÂ©trique ?', '01', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 4. u est-elle une suite gÃƒÂ©omÃƒÂ©trique ?', '10', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_0 = 1 et u_n+1 = u_n * 4. Que vaut u_4 ?', '0010', '16', '8', '64', '128'),
(1, 8, 'Facile', 'Quelle est la suite arithmÃƒÂ©tico-gÃƒÂ©omÃƒÂ©trique', '010', 'u_n+1 = u_n + a', 'u_n+1 = u_n * q + a', 'u_n+1 = u_n * q', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 16 et u_0 = 10. Quelle est la raison de u ?', '01', '10', '16', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 15 et u_0 = 12. Quelle est la raison de u ?', '10', '15', '12', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+2 = u_n+1 + u_n, u_0 = 0 et u_1 = 1. Que vaut u_4 ?', '0100', '2', '3', '4', '5'),
(1, 8, 'Facile', 'Soit u telle que u_0 = 10 et u_n+1 = u_n. Que vaut u_100 ?', '0100', '10 000', '10', '1000', '1000'),
(1, 9, 'Facile', 'Quel est l`ensemble des rÃƒÂ©sultats d`un dÃƒÂ© non pipÃƒÂ© ?', '0010', '{0, 1, 2, 3}', '{1, 3, 5}', '{1, 2, 3, 4, 5, 6}', '{2, 4, 6}'),
(1, 9, 'Facile', 'Soient A et B deux ÃƒÂ©vÃƒÂ¨nements. Que signifie A u B ?', '010', 'A inter B', 'A union B', 'A privÃƒÂ© de B', ''),
(1, 9, 'Facile', 'Soient A et B deux ÃƒÂ©vÃƒÂ¨nements. Quelle est la probabilitÃƒÂ© conditionnelle ?', '0001', 'P(A u B)', 'P(A n B)', 'P(A \ B)', 'P_A(B)'),
(1, 9, 'Facile', 'Soient A et B deux ÃƒÂ©vÃƒÂ¨enements. A n B signifie A inter B.', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Le cardinal d`un ensemble est le nombre d`ÃƒÂ©lÃƒÂ©ments de cet ensemble', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Soit A un ÃƒÂ©vÃƒÂ¨nement. Quelle est la probabilitÃƒÂ© de son ÃƒÂ©vÃƒÂ¨nement opposÃƒÂ© ?', '1000', '1 - P(A)', 'P(A) - 1', '1 / P(A)', '-P(A)'),
(1, 9, 'Facile', 'On lance 10 fois un dÃƒÂ© non pipÃƒÂ©. Quelle loi utiliser pour cette ÃƒÂ©tude ?', '01', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'On lance une fois un dÃƒÂ© non pipÃƒÂ©. Quelle loi utiliser pour cette ÃƒÂ©tude ?', '10', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Une variable alÃƒÂ©aoire n`associe par toujours une issure ÃƒÂ  un rÃƒÂ©el', '01', 'Vrai', 'Faux', '', ''),
(1, 10, 'Facile', 'Que vaut cos(0) ?', '010', '0', '1', 'Ã�Â€', ''),
(1, 10, 'Facile', 'Quelle proposition est fausse ?', '0100', 'sin(Ã¢ÂˆÂ’ÃŽÂ¸) = Ã¢ÂˆÂ’ sin(ÃŽÂ¸)', 'cosÃ‚Â²(x) - sinÃ‚Â²(x) = 1', 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)', 'sin(a + b) = sin(a)cos(b) + sin(b)cos(a)'),
(1, 10, 'Facile', 'Que vaut sin(Ã�Â€/6) ?', '01', 'Ã¢ÂˆÂš3 / 2', '1 / 2', '', ''),
(1, 10, 'Facile', 'Quel est le thÃƒÂ©orÃƒÂ¨me de BÃƒÂ©zout ?', '01', 'Soient a, b, c, si a divise bc et PGCD(a;b) = 1, alors a divise c', 'Soient a, b; si PGCD(a,b)=1 alors il existe u,v tq au + bv = 1', '', ''),
(1, 10, 'Facile', 'Qu`est ce que la congruence entre deux nombres a et b ?', '010', 'Lorsqu`il existe q tel que a = bq', 'Lorsqu`il existe k tel que a - b = kn', 'Lorsqu`il existe (q, r) tel que a = bq + r', ''),
(1, 10, 'Facile', 'Comment s`ÃƒÂ©crit l`ensemble des racines n-iÃƒÂ¨me de l`unitÃƒÂ© ?', '010', 'Q', 'U_n', 'UN', ''),
(1, 10, 'Facile', 'Quelle est la notation d`une racine n-iÃƒÂ¨me de l`unitÃƒÂ© ?', '1000', 'exp(i * 2 * k * Ã�Â€ / n) avec k dans [0, n - 1]', 'exp(iÃ�Â€/n)', 'exp(ik/n) avec k dans [0, n - 1]', 'exp(i * k * Ã�Â€ / n) avec k dans [0, n - 1]'),
(1, 10, 'Facile', 'Quelle est la notation exponentielle d`un nombre complexe ?', '0010', 'exp(i) = cos(iÃŽÂ¸)', 'exp(ÃŽÂ¸) = cos(i) + sin(i)', 'exp(iÃŽÂ¸) = cos(ÃŽÂ¸) + i*sin(ÃŽÂ¸)', 'exp(iÃŽÂ¸) = cos(ÃŽÂ¸) - i*sin(ÃŽÂ¸)'),
(1, 10, 'Facile', 'Comment s`ÃƒÂ©crit un nombre complexe ?', '0011', 'z = i', 'z = xi', 'z = xi + y', 'z = xi - y'),
(1, 11, 'Facile', 'Vrai ou Faux : (g o f)` = g` x (f` o g)', '01', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Vrai ou Faux : (fg)`= f`g + fg`', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Soit f une fonction continue et strictement monotone sur I, alors : ', '001', 'f rÃƒÂ©alise une injection de I sur J = f(I)', 'f rÃƒÂ©alise une surjection de I sur J = f(I)', 'f rÃƒÂ©alise une bijection de I sur J = f(I)', ''),
(1, 11, 'Facile', 'Quand dit-on qu`une fonction f est continue en a ?', '0010', 'Lorsqu`elle est dÃƒÂ©rivable en a', 'Lorsque la limite en a est non nulle', 'Lorsque la limite en a vaut f(a)', 'Lorsque f s`annule en a'),
(1, 11, 'Facile', 'Si f(x) <= g(x) <= h(x) et si f et h admettent une limite l en a, alors g admet une limite l en a', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Peut-il y avoir plusieurs limites pour une mÃƒÂªme valeur a ?', '01', 'Oui', 'Non', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en -inf de exp ?', '10', '0', '+inf', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en 0 de ln ?', '0100', '0', '-inf', '+inf', 'e'),
(1, 11, 'Facile', 'Qu`est ce qu`une fonction dite CADLAG ?', '010', 'Cosinus ÃƒÂ  droite, Logarithme ÃƒÂ  gauche', 'Continue ÃƒÂ  droite, Limite ÃƒÂ  gauche', 'Croissante ÃƒÂ  droite, linÃƒÂ©aire ÃƒÂ  gauche', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(A u B) = Card(A) + Card(B)', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Si A et B sont disjoints, Card(A u B) = Card(A) + Card(B)', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(E x F) = Card(E) x Card(F) oÃƒÂ¹ E et F sont deux ensembles', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Une variable alÃƒÂ©atoire rÃƒÂ©elle est une inconnue telle que x', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Quand dit-on que deux ÃƒÂ©vÃƒÂ¨nements sont indÃƒÂ©pendants ?', '010', 'Lorsque P(A u B) = P(A)P(B)', 'Lorsque P(A n B) = P(A)P(B)', 'Lorsque P(A u B) = P(A) + P(B)', ''),
(1, 12, 'Facile', 'Quand dit-on que deux ÃƒÂ©vÃƒÂ¨nements sont incompatibles ?', '0100', 'Lorsque P(A n B) = A', 'Lorsque P(A u B) = P(A) + P(B)', 'Lorsque P(A u B) = P(A)', 'Lorsque P(A) = P(B)'),
(1, 12, 'Facile', 'Quelle est la formule de Pascal ?', '0001', 'nCp = (n-1)Cp', 'nCp = (n+1)C(p+1)', 'nC(p-1) = (p+1)C(n-1)', 'nCp = (n-1)Cp + (n-1)C(p-1)'),
(1, 13, 'Facile', 'Quelle loi s`applique pour l`intensitÃƒÂ© du courant dans un circuit en sÃƒÂ©rie ?', '01', 'La loi d`additivitÃƒÂ©', 'La loi d`unicitÃƒÂ©', '', ''),
(1, 13, 'Facile', 'Qu`est ce que la loi d`additivitÃƒÂ© d`intensitÃƒÂ© ?', '0100', 'L`intensitÃƒÂ© d`une branche dÃƒÂ©rivÃƒÂ©e est ÃƒÂ©gale aux autres', 'L`intensitÃƒÂ© de la branche principale vaut la somme des dÃƒÂ©rivÃƒÂ©es', 'L`intensitÃƒÂ© d`une branche dÃƒÂ©rivÃƒÂ©e vaut la somme des autres', 'L`intensitÃƒÂ© est la mÃƒÂªme dans tout le circuit'),
(1, 13, 'Facile', 'Qu`est ce qu`un dipÃƒÂ´le ?', '01', 'Un composant magnÃƒÂ©tique avec deux pÃƒÂ´les', 'Un composant ÃƒÂ©lectrique avec deux bornes', '', ''),
(1, 13, 'Facile', 'Quand applique-t-on la loi d`additivitÃƒÂ© de la tension ?', '10', 'Un circuit en sÃƒÂ©rie', 'Un circuit en dÃƒÂ©rivation', '', ''),
(1, 13, 'Facile', 'Quelle est la loi d`Ohm ?', '0110', 'R = U x I', 'U = R x I', 'I = U / R', 'I = U x R'),
(1, 13, 'Facile', 'Comment mesure-t-on une intensitÃƒÂ© ?', '0001', 'Un voltmÃƒÂ¨tre en dÃƒÂ©rivation', 'Un voltmÃƒÂ¨tre en sÃƒÂ©rie', 'Un ampÃƒÂ¨remÃƒÂ¨tre en dÃƒÂ©rivation', 'Un ampÃƒÂ¨remÃƒÂ¨tre en sÃƒÂ©rie'),
(1, 13, 'Facile', 'Quelle est l`unitÃƒÂ© de l`intensitÃƒÂ© ?', '1000', 'AmpÃƒÂ¨re : A', 'Volt : V', 'Ohm : ÃŽÂ©', 'Watt : W'),
(1, 13, 'Facile', 'Comment calcule-t-on la puissance ÃƒÂ©lectrique ?', '0010', 'P = U x R', 'P = U / I', 'P = U x I', 'U = P x I'),
(1, 13, 'Facile', 'Quelle est l`unitÃƒÂ© de la puissance ÃƒÂ©lectrique ?', '0001', 'AmpÃƒÂ¨re : A', 'Volt : V', 'Ohm : ÃŽÂ©', 'Watt : W'),
(1, 13, 'Facile', 'Comment dÃƒÂ©terminer la valeur d`une rÃƒÂ©sistance ?', '0110', 'En la branchant en sÃƒÂ©rie avec une intensitÃƒÂ© ÃƒÂ©lectrique prÃƒÂ©dÃƒÂ©finie', 'En regardant son code couleur', 'En utilisant un ohmmÃƒÂ¨tre ÃƒÂ  l`extÃƒÂ©rieur du circuit', 'En utilisant un ohmmÃƒÂ¨tre ÃƒÂ  l`intÃƒÂ©rieur du circuit'),
(1, 13, 'Facile', 'Quelle est l`unitÃƒÂ© de la tension ?', '0100', 'AmpÃƒÂ¨re : A', 'Volt : V', 'Ohm : ÃŽÂ©', 'Watt : W'),
(1, 14, 'Facile', 'Sources de lumiÃƒÂ¨re : Quel est l`intrus ?', '001', 'Les sources primaires', 'Les objets diffusants', 'Les objets rÃƒÂ©flechissants', ''),
(1, 14, 'Facile', 'La trajectoire de la lumiÃƒÂ¨re est un mouvement ...', '0100', 'Circulaire', 'Rectiligne', 'Parabolique', 'SinusoÃƒÂ¯dal'),
(1, 14, 'Facile', 'Quelles sont les couleurs qui composent la lumiÃƒÂ¨re ?', '0100', 'Rouge Bleu Jaune', 'Toutes les couleurs de Violet ÃƒÂ  Rouge', 'Rouge Vert Bleu', 'Magenta Jaune Cyan'),
(1, 14, 'Facile', 'A quoi est dÃƒÂ»e la couleur d`un objet', '1100', 'Aux pigments prÃƒÂ©sents sur l`objet', 'A la lumiÃƒÂ¨re ÃƒÂ©clairant l`objet', 'A la lumiÃƒÂ¨re que l`objet absorbe' , 'Au rayonnement naturel de l`objet'),
(1, 14, 'Facile', 'Quel comportement a la lumiÃƒÂ¨re avec une lentille convergente ?', '10', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quel comportement a la lumiÃƒÂ¨re avec une lentille divergente ?', '01', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quelle est la vitesse de la lumiÃƒÂ¨re ?', '0010', '300 km/s', '3 000 m/s', '300 000 km/s', '300 000 m/s'),
(1, 14, 'Facile', 'Vrai ou Faux : Un oeil est comparable ÃƒÂ  une lentille avec un ÃƒÂ©cran', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La lumiÃƒÂ¨re a la mÃƒÂªme vitesse quelque soit le milieu', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Magenta Jaune et Cyan sont les composantes principales de la lumiÃƒÂ¨re', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Utiliser deux couleurs de lumiÃƒÂ¨re permet d`en obtenir une autre', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La vitesse de la lumiÃƒÂ¨re sert ÃƒÂ  mesurer des distances spatiales', '10', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Interactions : Quel est l`intrus ?', '001', 'L`interaction magnÃƒÂ©tique', 'L`interaction gravitationnelle', 'L`interaction mÃƒÂ©canique', ''),
(1, 15, 'Facile', 'Qu`est ce que le poids d`un objet ?', '01', 'La quantitÃƒÂ© de matiÃƒÂ¨re d`un objet', 'L`action gravitationnelle exercÃƒÂ©e sur cet objet', '', ''),
(1, 15, 'Facile', 'Qu`est ce que la masse d`un objet ?', '10', 'La quantitÃƒÂ© de matiÃƒÂ¨re d`un objet', 'L`action gravitationnelle exercÃƒÂ©e sur cet objet', '', ''),
(1, 15, 'Facile', 'Quelle est la relation entre le poids et la masse ?', '0010', 'P = m / g', 'm = P x g', 'P = m x g', 'g = m x P'),
(1, 15, 'Facile', 'Qu`est ce que l`ÃƒÂ©nergie ?', '010', 'Une quantitÃƒÂ© de mouvement', 'La capacitÃƒÂ© d`un objet ÃƒÂ  agir sur lui mÃƒÂªme et les autres', 'Une quantitÃƒÂ© de tempÃƒÂ©rature', ''),
(1, 15, 'Facile', 'Qu`est ce que l`ÃƒÂ©nergie de position ?', '10', 'Une ÃƒÂ©nergie dÃƒÂ©pendant de la hauteur', 'Une ÃƒÂ©nergie dÃƒÂ©pendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`ÃƒÂ©nergie cinÃƒÂ©tique ?', '01', 'Une ÃƒÂ©nergie dÃƒÂ©pendant de la hauteur', 'Une ÃƒÂ©nergie dÃƒÂ©pendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`ÃƒÂ©nergie mÃƒÂ©canique ?', '01', 'Un terme gÃƒÂ©nÃƒÂ©ral pour parler de l`ÃƒÂ©nergie, cinÃƒÂ©tique ou de position', 'La comme de l`ÃƒÂ©nergie cinÃƒÂ©tique et de l`ÃƒÂ©nergie de position', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la formule de l`ÃƒÂ©nergie cinÃƒÂ©tique est m x vÃ‚Â²', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la masse n`influe pas sur l`ÃƒÂ©nergie cinÃƒÂ©tique', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la vitesse influe sur l`ÃƒÂ©nergie cinÃƒÂ©tique', '10', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Un mouvement en ligne droite est qualifié de mouvement', '0010', 'Circulaire', 'Curviligne', 'Rectiligne', 'Uniforme'),
(1, 15, 'Facile', 'Un mouvement en forme de cercle est qualifié de', '100', 'Circulaire', 'Quelconque', 'Rectiligne', 'Uniforme'),
(1, 15, 'Facile', 'Autour de quelle étoile la Terre tourne-t-elle?', '010', 'La Lune', 'Le Soleil', 'Jupiter', ''),
(1, 15, 'Facile', 'Pourquoi la Lune brille-t-elle?', '001', 'Elle est habitée', 'La Terre l\'éclaire', 'Le Soleil l\'éclaire', ''),
(1, 15, 'Facile', 'Une révolution est', '0001', 'Un tour complet du Soleil autour de la Terre', 'Un Tour complet de la Terre autour de la Lune', 'Un tour de la Terre sur elle même.', 'Un tour complet de la Terre autour du soleil'),
(1, 16, 'Facile', 'Qu`est ce qu`un noeud ?', '010', 'Un dipÃƒÂ´le', 'Un point de connexion entre au moins 3 dipÃƒÂ´les', 'Une partie de circuit', ''),
(1, 16, 'Facile', 'Qu`est ce qu`une maille  ?', '001', 'Un dipÃƒÂ´le', 'Une partie de circuit', 'Une boucle fermÃƒÂ©e', ''),
(1, 16, 'Facile', 'Quelle est la loi des noeuds ?', '10', 'Somme des intensitÃƒÂ©s entrantes = Somme des intensitÃƒÂ©s sortantes', 'Somme des tensions entrantes = Somme des tensions sortantes', '', ''),
(1, 16, 'Facile', 'Quelle est la loi des mailles ?', '01', 'La somme des intensitÃƒÂ©s dans une maille est nulle', 'La somme des tensions dans une maille est nulle', '', ''),
(1, 16, 'Facile', 'Comment reprÃƒÂ©sente t on la caractÃƒÂ©ristique d`un dipÃƒÂ´le', '01', 'Un graphe Volt en x AmpÃƒÂ¨re en y', 'Un graphe AmpÃƒÂ¨re en x Volt en y', '', ''),
(1, 17, 'Facile', 'Qu`est ce qu`une onde mÃƒÂ©canique ?', '0110', 'Un onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matiÃƒÂ¨re', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Qu`est ce qu`une onde ÃƒÂ©lectromagnÃƒÂ©tique', '1001', 'Une onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matiÃƒÂ¨re', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Quel est le symbÃƒÂ´le de la frÃƒÂ©quence d`une onde sonore', '01', 'f (frÃƒÂ©quence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Quel est l`unitÃƒÂ© de la frÃƒÂ©quence d`une onde sonore', '10', 'f (frÃƒÂ©quence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : l`intensitÃƒÂ© sonore est exprimÃƒÂ©e en Watt', '01', 'Vrai', 'Faux', '', ''), 
(1, 17, 'Facile', 'Vrai ou Faux : une onde est doublement pÃƒÂ©riodique', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Lors de la propagation d`une onde il y a dÃƒÂ©placement de matiÃƒÂ¨re', '01', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Une onde est un transport d`ÃƒÂ©nergie', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Quand dit on qu`une onde mÃƒÂ©canique est progressive', '010', 'Lorsqu`elle accÃƒÂ©lÃƒÂ¨re progressivement', 'Lorsqu`elle se propage de proche en proche', 'Lorsqu`elle ralentit progressivement', ''),
(1, 17, 'Facile', 'Pour parler de la vitesse de propragation d`une onde on parle de ...', '01', 'Vitesse', 'CÃƒÂ©lÃƒÂ©ritÃƒÂ©', '', ''),
(1, 17, 'Facile', 'L\'unité SI de fréquence est', '010', 'Joule', 'Hertz ', 'Coulomb', ''),
(1, 17, 'Facile', 'Lorsque le mouvement d\'une particule vibrante est perpendiculaire à la direction de l\'onde, il est appelé le mouvement d\'onde ', '10', 'transversale ', 'longitudinale', '', ''),
(1, 17, 'Facile', 'Un son grave est moins criard par nature', '01', 'Faux', 'Vrai', '', ''),
(1, 18, 'Moyenne', 'Quels sont les milieux transparents traversés par les rayons de lumière qui pénètrent dans l\'œil ?', '100', 'La cornée, l\'humeur aqueuse, la pupille, le cristallin', 'La cornée, la rétine, l\'humeur vitrée', 'L\'iris, l\'humeur aqueuse, le cristallin', ''),
(1, 18, 'Moyenne', 'Où se forme l\'image ?', '010', 'Dans l\'oeil', 'Sur la rétine', 'Dans le cristallin', ''),
(1, 18, 'Difficile', 'Comment se comportent les parallèles d\'un faisceau qui émerge d\'une lentille convergente', '0001', 'En restent parallèles mais en s\'inclinant selon un certain angle', 'En restant parallèle', 'En Divergeant', 'En convergeant'),
(1, 18, 'Difficile', 'Comment émerge une lentille convergente un rayon passant par son centre optique O?', '1000', 'Sans être devié', 'En passant par son foyer image F\'', 'Parallèlement à l\'axe optique', 'En passant par son foyer objet F'),
(1, 18, 'Difficile', 'Où une lentielle convergente forme-t-elle un objet situé à l\'inifini', '0010', 'Dans son plan focal image', 'Dans sono plan focal objet', 'A l\'infini', 'Sur son centre optique'),
(1, 18, 'Difficile', 'Quel élément de l\'oeil joue le rôle de lentille', '001', 'L\'iris', 'Le Cristallin', 'La pupille', ''),
(1, 18, 'Difficile', 'Quel élément de l\'oeil joue le rôle d\'écran', '1000', 'La rétine', 'L\'iris', 'Le Cristallin', 'La pupille'),
(1, 19, 'Facile', 'L\'énergie potentielle de pesanteur d\'un corps dépend :', '0111', 'de sa vitesse', 'de sa masse ', 'de son altitude', 'de sa position à la surface de la Terre'),
(1, 19, 'Facile', ' L\'énergie cinétique d\'un corps dépend :', '0101', 'de sa vitesse', 'de son altitude', ' de sa masse', 'de l\'intensité de la pesanteur g'),
(1, 19, 'Moyenne', 'L\'énergie cinétique d\'une balle de masse m = 100 g dont la vitesse est de 36,0 km.h-1 est de', '1000', '5,00 J', '5,00×103 J', '64,8 J', '6,48×104 J'),
(1, 19, 'Difficile', ' Un système est dit conservatif si :', '0011', 'son énergie cinétique se conserve', 'son énergie potentielle de pesanteur se conserve', 'il n\'échange pas d\'énergie avec le milieu extérieur', 'il n\'échange pas d\'énergie avec le milieu extérieur'),
(1, 19, 'Difficile', 'Un transfert thermique (hors rayonnement) entre deux corps :', '010', 's\'effectue toujours lorsque deux corps sont en contact', 's\'effectue toujours du corps chaud vers le corps froid.', 'n\'a pas besoin d\'un milieu matériel pour s\'effectuer', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 40, 'Facile', 'OÃƒÂ¹ ont ÃƒÂ©tÃƒÂ© trouvÃƒÂ©s les plus vieux ossements humains ?', '1000', 'En Afrique', 'En Asie', 'En Europe', 'En AmÃƒÂ©rique'),
(1, 40, 'Facile', 'L`homme moderne est un', '10', 'Homo sapiens', 'Home neandertalis', '', ''),
(1, 41, 'Facile', 'L`ÃƒÂ©criture de l`Egypte antique se nomme', '10', 'HiÃƒÂ©roglyphe', 'Cursive', '', ''),
(1, 41, 'Facile', 'ClÃƒÂ©opÃƒÂ¢tre rÃƒÂ©gna sur l`Egypte vers', '1000', '40 avant JÃƒÂ©sus-Christ', '400 avant JÃƒÂ©sus-Christ', '40 aprÃƒÂ¨s JÃƒÂ©sus-Christ', '400 aprÃƒÂ¨s JÃƒÂ©sus-Christ'),
(1, 41, 'Facile', 'Vrai ou Faux : VercingÃƒÂ©torix ÃƒÂ©tait un soldat romain', '01', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Vrai ou Faux : VercingÃƒÂ©torix a dÃƒÂ©posÃƒÂ© les armes ÃƒÂ  Alexia', '10', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Jules CÃƒÂ©sar est un personnage datant de', '1000', 'L`AntiquitÃƒÂ©', 'Le Moyen-ÃƒÂ¢ge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Clovis est nÃƒÂ© vers', '010', '1180', '466', '1980', ''),
(1, 42, 'Facile', 'Jeanne d`Arc est un personnage datant de', '0100', 'L`AntiquitÃƒÂ©', 'Le Moyen-ÃƒÂ¢ge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Vrai ou Faux : Dagobert 1er rÃƒÂ©gna avant Clovis', '01', 'Vrai', 'Faux', '', ''),
(1, 42, 'Facile', 'Quelle dynastie succÃƒÂ©da ÃƒÂ  celle des MÃƒÂ©rovingiens ?', '1000', 'Les Carolingiens', 'Les CapÃƒÂ©tiens', 'Les Valois', 'Les Bourbons'),
(1, 42, 'Facile', 'Charlemagne ÃƒÂ©tait le fils de ', '010', 'Clovis', 'PÃƒÂ©pin le Bref', 'Hugues Capet', ''),
(1, 42, 'Facile', 'Sous quels autres noms connaÃƒÂ®t-on Louis IX', '110', 'Saint-Louis', 'Le Prudhomme', 'Louis le Bon', ''),
(1, 43, 'Facile', 'Quel ÃƒÂ©lÃƒÂ©ment n`est pas du Moyen-ÃƒÂ‚ge ?', '001', 'Les chÃƒÂ¢teaux forts', 'Les chevaliers', 'Les montgolfiÃƒÂ¨res', ''),
(1, 43, 'Facile', 'A qui doit-on l`invention de l`imprimerie ?', '0100', 'LÃƒÂ©onard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'A qui doit-on l`invention de la machine ÃƒÂ  vapeur ?', '0010', 'LÃƒÂ©onard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'LÃƒÂ©onard de Vinci a travaillÃƒÂ© pour ', '0100', 'Jules CÃƒÂ©sar', 'FranÃƒÂ§ois 1er', 'Louis XIV', 'NapolÃƒÂ©on'),
(1, 43, 'Facile', 'Parmi ces personnages qui ÃƒÂ©taient explorateurs ?', '1110', 'Marco Polo', 'Magellan', 'Christophe Collomb', 'Guttenberg'),
(1, 44, 'Facile', 'Louis XIV ÃƒÂ©tait surnommÃƒÂ©', '10', 'Le roi Soleil', 'Le roi fainÃƒÂ©ant', '', ''),
(1, 44, 'Facile', 'MoliÃƒÂ¨re ÃƒÂ©tait ', '001', 'Chevalier', 'Roi', 'Ecrivain', ''),
(1, 44, 'Facile', 'La RÃƒÂ©volution FranÃƒÂ§aise a eu lieu en ', '0100', '1515', '1789', '1804', '1968'),
(1, 44, 'Facile', 'La Bastille ÃƒÂ©tait ', '100', 'Une prison', 'La rÃƒÂ©sidence du Roi', 'Une auberge', ''),
(1, 44, 'Facile', 'Quel roi fut guillotinÃƒÂ© ?', '010', 'Henri IV', 'Louis XVI', 'Louis-Philippe', ''),
(1, 44, 'Facile', 'NapolÃƒÂ©on Bonaparte devint empereur des FranÃƒÂ§ais en ', '001', '800', '1792', '1804', ''),
(1, 44, 'Facile', 'Le GÃƒÂ©nÃƒÂ©ral de Gaulle a combattu', '0001', 'Les Romains avec VercingÃƒÂ©torix', 'Les Anglais avec Jeanne d`Arc', 'Les Russes avec NapolÃƒÂ©on', 'Les Allemands avec Churchill'),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 48, 'Facile', 'Combien y a-t-il de continents ?', '001', '2', '4', '6', ''),
(1, 48, 'Facile', 'Quel fleuve n`est pas un fleuve FranÃƒÂ§ais ?', '0010', 'La Garonne', 'La Loire', 'Le Nil', 'La Seine'),
(1, 48, 'Facile', 'Quel est le plus long fleuve de France ?', '0001', 'La Garonne', 'Le RhÃƒÂ´ne', 'La Seine', 'La Loire'),
(1, 48, 'Facile', 'Quels massifs montagneux sont en France ?', '1110', 'Les Alpes', 'Les PyrennÃƒÂ©es', 'Le Massif Central', 'L`Himalaya'),
(1, 48, 'Facile', 'Combien y a t-il de saisons en Europe ?', '10', '4', '2', '', ''),
(1, 48, 'Facile', 'En hiver, les nuits sont', '100', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Au printemps, les nuits sont', '010', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Combien y a-t-il de jours dans une annÃƒÂ©e ?', '100', '365-366 jours', '255-256 jours', '405-406 jours', ''),
(1, 48, 'Facile', 'Combien de jours comprend le mois de Mars ?', '001', '29', '30', '31', ''),
(1, 48, 'Facile', 'Une annÃƒÂ©e de 366 jours s`appelle une annÃƒÂ©e ...', '010', 'bipolaire', 'bissextile', 'bipode', ''),
(1, 48, 'Facile', 'Une annÃƒÂ©e bissextile arrive tous les ', '1000', '4 ans', '5 ans', '6 ans', '7 ans'),
(1, 48, 'Facile', 'Vrai ou Faux : Le Soleil tourne autour de la Terre', '01', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Terre tourne sur elle-mÃƒÂªme', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Lune tourne autour de la Terre', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'La Lune tourne autour de la Terre en environ', '1000', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre tourne autour du Soleil en ', '0001', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre fait un tour sur elle-mÃƒÂªme en ', '100', '1 jour', '1 mois', '1 an', ''),
(1, 48, 'Facile', 'Une journÃƒÂ©e dure ', '10', '24 heures', '12 heures', '', ''),
(1, 48, 'Facile', 'Le Soleil se lÃƒÂ¨ve', '1000', 'ÃƒÂ  l`Est', 'ÃƒÂ  l`Ouest', 'au Nord', 'au Sud'),
(1, 48, 'Facile', 'Comment appelle-t-on Nord, Est, Ouest, Sud', '001', 'Les points noirs', 'Les points blancs', 'Les points cardinaux', ''),
(1, 48, 'Facile', 'Quelles mers bordent la France ?', '101', 'Mer mÃƒÂ©diterrannÃƒÂ©e', 'Mer rouge', 'La Manche', ''),
(1, 48, 'Facile', 'A combien culmine le Mont Blanc ?', '100', '4807', '8848', '5891', ''),
(1, 48, 'Facile', 'Quels pays ont frontiÃƒÂ¨re commune avec la France ?', '110', 'La Belgique', 'L`Allemagne', 'La Russie', ''),
(1, 48, 'Facile', 'Quelle la capitale de la France ?', '100', 'Paris', 'Lille', 'Marseille', ''),
(1, 48, 'Facile', 'Combien de pays comprend l`union europÃƒÂ©enne ?', '010', '17', '27', '37', ''),
(1, 49, 'Difficile', 'Autrefois la Birmanie, aujourdhui ', '100', 'Myanmar', 'Magyar', 'Malawi', ''),
(1, 49, 'Difficile', 'La RhodÃ©sie du Sud fut ainsi nommÃ©e de 1895 jusqu\'en 1980 oÃ¹ elle devient', '010', 'Le Zimbabwe', 'Le ZambÃ¨ze', 'La Zambie', ''),
(1, 49, 'Difficile', 'Le royaume de siam Ã  Ã©tÃ© fondÃ© en 1350 et devient en 1939 le royaume de', '10', 'ThaÃ¯lande', 'Pagan', '', ''),
(1, 49, 'Moyenne', 'La tchÃ©coslovaquie est un Etat souvrain qui exista de 1918 Ã  1992 avant de devenir suite Ã  sa dissolution', '001', 'La TchÃ©quie', 'La Slovaquie', 'La Slovaquie et la TchÃ©quie', ''),
(1, 49, 'Moyenne', 'D\'abord colonie de l\'AOF en 1919, la Haute-Volta fut une rÃ©publique en 1958 afin de devenir en 1984', '0001', 'La GuinÃ©e', 'Le Rwanda', 'La Mozambique', 'Le Burkina Faso'),
(1, 49, 'Difficile', 'En 1894, l\'empire colonial franÃ§ais intÃ¨gre le royaume du Dahomey Ã  l\'AOF qui deviendra en 1960, la rÃ©publique du Dahomey avant de devenir en 1990 rÃ©publique du ', '010', 'Lesotho', 'BÃ©nin', 'Burundi', ''),
(1, 49, 'Difficile', 'Le Swaziland, petite monarchie enclavÃ©e au sud de l\'Afrique, prit en 2018 le nom de', '10', 'Eswatini', 'Nambie', '', ''),
(1, 49, 'Facile', 'La rÃ©publique du ZaÃ¯re Ã©tait le nom de l\'actuelle', '0100', 'RÃ©publique de GuinÃ©e Equatoriale', 'RÃ©publique DÃ©mocratique du Congo', 'RÃ©publique Centrafricaine', 'RÃ©publique du Congo'),
(1, 49, 'Facile', 'Les ocÃ©ans recouvrent combien de % sur la Terre ?', '1000', '70.8', '65.8', '20.8', '90.8'),
(1, 49, 'Facile', 'En mÃ¨tres, quelle est la profondeur de l\'ocÃ©an Pacifique ?', '0010', '5 000 m', '3 000 m', '10 925 m', '15 000 m'),
(1, 49, 'Facile', 'Pour 1Kg d\'eau de mer, combien a-t-on de grammes de sel ?', '0001', '10 Ã  20 g', '100 g', '60 Ã  70 g', '30 Ã  40 g'),
(1, 49, 'Facile', 'On dit que les marÃ©es sont influencÃ©es par la Lune. Est-ce vrai ou faux ?', '01', 'Faux', 'Vrai', '', ''),
(1, 49, 'Facile', 'En pourcentage, quelle est la superficie totale des ocÃ©ans Ã  la surface de notre planÃ¨te ?', '1000', '71%', '61%', '51%', '81%'),
(1, 49, 'Facile', 'Quelle est la particularitÃ© des ocÃ©ans de notre planÃ¨te ?', '010', 'Les ocÃ©ans ne sont pas composÃ©s avec de l\'eau', 'Tous les ocÃ©ans sont reliÃ©s entre eux', 'On ne pas passÃ© d\'un ocÃ©an Ã  un autre car ils sont bloquÃ©s par les continent', ''),
(1, 49, 'Facile', 'Combien y-a-t-il d\'ocÃ©ans sur la Terre ?', '0001', '4', '3', '6', '5'),
(1, 49, 'Moyenne', 'A l\'Ã©chelle mondiale, le commerce de marchandises se fait essentiellement par quelle voie', '0100', 'AÃ©rienne', 'Maritime', 'Ferroviaire', 'RoutiÃ¨re'),
(1, 49, 'Moyenne', 'Quelle est la part des Ã©changes commerciaux s\'effectuant par voie maritime ?', '0010', '50%', '70%', '80%', '100%'),
(1, 49, 'Facile', 'Quel est le plus grand port du monde ?', '0100', 'Bordeaux', 'ShanghaÃ¯', 'Rotterdam', 'Singapour'),
(1, 49, 'Moyenne', 'Sur les 10 premiers ports du monde, combien sont chinois ?', '100', '7', '3', '5', ''),
(1, 49, 'Facile', 'Quel est le 1er port d\'Europe ?', '0001', 'Marseille/fos-sur-Mer', 'Le Havre', 'Barcelone', 'Rotterdam'),
(1, 49, 'Facile', 'Qu\'est-ce qu\'un canal ?', '001', 'Un passage Ã©troit mais natural entre deux ocÃ©ans', 'Un passage Ã©troit mais natural entre deux mers', 'Une riviÃ¨re artificielle creusÃ©e par l\'Homme', ''),
(1, 49, 'Moyenne', 'Quels ocÃ©ans sont reliÃ©s par le canal de Panama ?', '0100', 'Atlantique et Indien', 'Atlantique et Pacifique', 'Pacifique et Indien', 'Atlantique et Glacial Arctique'),
(1, 49, 'Facile', 'Qu\'est-ce qu\'un dÃ©troit ?', '0001', 'Un riviÃ¨re artificielle creusÃ©e par l\'homme', 'Bande de mer Ã©troite entre deux Ã©tendues de mers ou d\'ocÃ©ans', 'Un dÃ© Ã  trois faces', 'Bande de mer Ã©troite entre deux Ã©tendues de terre'),
(1, 49, 'Moyenne', 'Les espaces marins ont un rÃ´le de rÃ©gulateur climatique vitale pour l\'humanitÃ© ?', '1000', 'Vrai', 'Faux', 'Seulement la nuit', 'Seulement la journÃ©e'),
(1, 49, 'Moyenne', 'Dans quel dÃ©partement se trouve le GrÃ©sivaudan ?', '010', 'La LozÃ¨re', 'l\'IsÃ¨re', 'La Haute-Loire', ''),
(1, 50, 'Moyenne', 'Dans quel dÃ©partement se trouve le chÃ¢teau de Malesherbes ?', '10', 'Le Loiret', 'L\'Aisne', '', ''),
(1, 50, 'Moyenne', 'Dans quel dÃ©partement se trouve la forÃªt d\'Hourtin ?', '001', 'L\'Yonne', 'Le Bas-Rhin', 'La Gironde', ''),
(1, 50, 'Moyenne', 'Dans quel dÃ©partement se trouve la ville fortifiÃ©e de Saint-Bonnet-le-ChÃ¢teau ?', '010', 'Les PyrÃ©nÃ©es-Atlantiques', 'La Loire', 'Les Hautes-PyrÃ©nÃ©es', ''),
(1, 50, 'Moyenne', 'Dans quel dÃ©partement se trouve la basilique Notre-Dame-de-Buglose ?', '001', 'La Creuse', 'Le Cher', 'Les Landes', ''),
(1, 50, 'Moyenne', 'Parmi ces Ã©tats lequel est traversÃ© par l\'Equateur ?', '1000', 'L\'IndonÃ©sie', 'L\'Argentine', 'L\'Afrique du Sud', 'L\'Afganistan'),
(1, 50, 'Facile', 'La GuinÃ©e est un pays...?', '0100', 'D\'Europe', 'D\'Afrique', 'D\'AmÃ©rique', 'D\'OcÃ©anie'),
(1, 50, 'Moyenne', 'Parmi ces villes laquelle se trouve la plus au nord ?', '0010', 'Nairobi', 'Pretoria', 'Tombouctou', 'Bujumbura'),
(1, 50, 'Difficile', 'Parmi ces pays lequel est le plus vaste ?', '0001', 'La Lituanie', 'La Letonie', 'La GÃ©orgie', 'La NorvÃ¨ge'),
(1, 50, 'Difficile', 'Odessa est une grande ville d...?', '010', 'Du Canada', 'D\'Ukraine', 'De Russie', ''),
(1, 50, 'Moyenne', 'Lagos est une grande ville ...?', '001', 'Du Kenya', 'D\'Afrique du Sud', 'Du NigÃ©ria', ''),
(1, 50, 'Moyenne', 'Parmi ces Ã©tats lequel est un pays de l\'hÃ©misphÃ¨re sud ?', '1000', 'L\'Angola', 'La Chine', 'Le SÃ©nÃ©gal', 'Le Soudan'),
(1, 50, 'Facile', 'Lequel de ces pays a dÃ©jÃ  mis seul un satellite en orbite ?', '1OO', 'La CorÃ©e du Sud', 'La Turquie', 'Le PÃ©rou', ''),
(1, 50, 'Difficile', 'Parmi ces pays lequel touche les Carpates ?', '01', 'La GrÃ¨ce', 'La Slovaquie', '', ''),
(1, 50, 'Moyenne', 'Pamis ces pays lequel est le plus vaste ?', '001', 'L\'Equateur ', 'L\'Urugay', 'L\'Argentine', ''),
(1, 50, 'Moyenne', 'Quelle mer ou OcÃ©an est bordÃ© par le Liberia ?', '0001', 'OcÃ©an Indien', 'La mer Rouge', 'La mer Noire', 'L\'OcÃ©an Atlantique'),
(1, 50, 'Difficile', 'Parmie ces nations laquelle est la plus peuplÃ©e ?', '0100', 'Le Cambodge', 'Le Viet-Nam', 'Le Laos', 'La ThaÃ¯lande'),
(1, 50, 'Moyenne', 'Quel est le nombre d\'habitants de la France ? (en millions)', '1000', '66', '21', '32', '134'),
(1, 50, 'Difficile', 'Oman est...', '0010', 'Un Royaume', 'Une rÃ©publique Populaire', 'Un Sultanat', 'Un Ã©mirat'),
(1, 50, 'Facile', 'Parmi ces pays lequel n\'est pas limitrophes Ã  la Pologne?', '010', 'Bielorussie', 'Hongrie', 'Lituanie', ''),
(1, 50, 'Moyenne', 'Parmi ces villes laquelle se trouve le plus au nord ?', '0001', 'Lagos', 'Addis-Abebas', 'Brazzaville', 'Alger'),
(1, 50, 'Difficile', 'Parmi ces Ã©tats lequel est un pays d\'Afrique australe ?', '001', 'La Birmanie', 'Le Tchad', 'Le Zimbabwe', ''),
(1, 50, 'Difficile', 'Dans quel pays coule l\'Ebre ?', '01', 'Le Portugal', 'L\'Espagne', '', ''),
(1, 50, 'Difficile', 'Parmi ces pays lequel n\'a pas d\'accÃ¨s Ã  la mer ?', '1000', 'Le Bostwana', 'La Nambie', 'Le Kenya', 'L\'Angola'),
(1, 50, 'Moyenne', 'Parmi ces villes laquelle se trouve la plus au sud ?', '001', 'Madrid', 'Istambul', 'Tokyo', ''),
(1, 50, 'Moyenne', 'Parmi ces Ã©tats lequel est traversÃ© par l\'Equateur ?', '010', 'La Syrie', 'La Colombie', 'La Tunisie', ''),
(1, 51, 'Difficile', 'Parmi ces pays lequel est le plus vaste ?', '1000', 'Niger', 'NigÃ©ria', 'Cameroun', 'Burkina Faso'),
(1, 51, 'Difficile', 'Auckland est une grande ville de quel pays ?', '010', 'IndonÃ©sie', 'Nouvelle ZÃ©lande', 'Paragey', ''),
(1, 51, 'Moyenne', 'Lequel de ces pays est dans l\'Union EuropÃ©enne ?', '0100', 'NorvÃ¨ge', 'Hongrie', 'Islande', 'Moldavie'),
(1, 51, 'Difficile', 'Parmi ces pays lequel touche l\'Himalaya ?', '0001', 'L\'Iran', 'La Mongolie', 'Le Laos', 'Le Bhoutan'),
(1, 51, 'Difficile', 'Quelle mer ou OcÃ©an est bordÃ© par la NorvÃ¨ge ?', '1000', 'Mer de Barents', 'Mer de Laptev', 'Mer Baltique', 'OcÃ©an Pacifique'),
(1, 51, 'Facile', 'Parmi ces pays lequel n\'est pas limitrophes Ã  la Russie ?', '0010', 'Pologne', 'CorÃ©e du Nord', 'Moldavie', 'NorvÃ¨ge'),
(1, 51, 'Difficile', 'Altitude de l\'Everest ?', '0001', '8648 m', '8748 m', '8948 m', '8848 m'),
(1, 51, 'Difficile', 'Quel est le 2Ã¨me plus haut sommet du monde ?', '0100', 'Lhose', 'K2', 'Kangchenjunga', 'Makalu'),
(1, 51, 'Difficile', 'Dans quelle chaine de montagnes se situe l\'Aconcagua ?', '100', 'CordiliÃ¨re des Andes', 'Caucase', 'Montagne rocheuses', ''),
(1, 51, 'Moyenne', 'Quel est le point culminant du continent africain ?', '0001', 'Mont Kenya', 'Mont Speke', 'Mont Stanley', 'Kilimandjaro'),
(1, 51, 'Moyenne', 'Quel est le deuxiÃ¨me sommet des Alpes aprÃ¨s le Mont Blanc ?', '01', 'Mont Cervin', 'Mont Rose', '', ''),
(1, 51, 'Moyenne', 'Point culminant de l\'Espagne ?', '10', 'Teide', 'Pic Aneto', '', ''),
(1, 51, 'Difficile', 'Combien y a-t-il de sommets de + de 8 000 m sur la planÃ¨te ?', '0001', '10', '16', '12', '14'),
(1, 51, 'Difficile', 'OÃ¹ se situe le Mont Mac Kingley ?', '0100', 'Patagonie', 'Alaska', 'GroÃ«nland', 'CordiliÃ¨res des Andes'),
(1, 51, 'Difficile', 'OÃ¹ se situe le Mont Elbrouz ?', '001', 'Alpes', 'Domolites', 'Caucase', ''),
(1, 51, 'Difficile', 'Quel est le point culminant du massif de la Vanoise ?', '100', 'La Grande Casse', 'La Grande Motte', 'Le Mont Pourri', ''),
(1, 51, 'Facile', 'Quel fleuve passe par la ville du Caire ?', '010', 'L\'AssioÃ»t', 'Le Nil', 'Le Nasser', ''),
(1, 51, 'Moyenne', 'Quel fleuve passe par la ville de la Nouvelle-OrlÃ©ans ?', '001', 'Red', 'Rio Grande', 'Mississipi', ''),
(1, 51, 'Difficile', 'Quel fleuve passe par la ville de Lisala ?', '100', 'Congo', 'Sankuru', 'Tshuapa', ''),
(1, 51, 'Facile', 'Quel fleuve passe par la ville de Bordeaux ?', '001', 'La Loire', 'Le RhÃ´ne', 'La Garonne', ''),
(1, 51, 'Moyenne', 'Quelle capitale europÃ©enne abrite la Grand-Place, renommÃ©e pour sa richesse ornementale ?', '0100', 'Vienne', 'Bruxelles', 'Amsterdam', 'Paris'),
(1, 51, 'Moyenne', 'OÃ¹ situez-vous le site mÃ©galithique de Stonehenge ?', '100', 'An Agleterre', 'En Ecosse', 'Au Pays de Galles', ''),
(1, 51, 'Difficile', 'Quelle est l\'unitÃ© monÃ©taire et la devise d\'HaÃ¯ti ?', '010', 'La Cruche', 'La Gourde', 'La Courge', ''),
(1, 51, 'Difficile', 'OÃ¹ devez-vous vous rendre pour admirer le temple de Borobudur ?', '100', 'En IndonÃ©sie', 'En Malasie', 'En ThaÃ¯lande', ''),
(1, 51, 'Difficile', 'Quel pays d\'Afrique de l\'Ouest correspond au territoire de l\'ancien Royaume de Dahomey ?', '001', 'Le Togo', 'Le Ghana', 'Le BÃ©nin', ''),
(1, 52, 'Facile', 'Quels verbes sont du 1er groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 2ÃƒÂ¨me groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ÃƒÂ¨me groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ÃƒÂ¨me groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'PrÃƒÂ©sent  : Vous (manger)', '01', '', '', '', ''),
(1, 52, 'Facile', 'Futur : Vous (courir)', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', 'Imparfait : Ils (finir)', '', '', ''),
(1, 53, 'Facile', '', '01', 'PassÃƒÂ© ComposÃƒÂ© : Tu (aller)', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : On entend le rossignol chanter', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : La fusÃƒÂ©e dÃƒÂ©collera ÃƒÂ  12 heures', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : Nous ÃƒÂ©tions les rois du monde', '', '', ''),
(1, 53, 'Facile', '', '01', 'OÃƒÂ¹ est le verbe : Le chat mange une souris', '', '', ''),
(1, 53, 'Facile', '', '01', 'Qui est le nom noyau : La petite fille aux alumettes', '', '', ''),
(1, 53, 'Facile', '', '01', 'Combien de verbes : Le chat suit des yeux le mulot, se tapit, puis bondit dessus', '', '', ''),
(1, 53, 'Facile', '', '01', 'COD ou COI (une souris) : Le chat mange une souris', '', '', ''),
(1, 53, 'Facile', '', '01', 'COD ou COI (ÃƒÂ  sa grand-mÃƒÂ¨re) : La fille ÃƒÂ©crit ÃƒÂ  sa grand-mÃƒÂ¨re', '', '', ''),
(1, 53, 'Facile', '', '01', 'Nature de "Sous le rebord de la fenÃƒÂªt', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', '');

/* Ajout Questions Forum */

INSERT INTO forumQuestion(question, id_student, answer)
VALUES('Question1', 1, ''),
('Question2', 1, ''),
('Question3', 1, ''),
('Question4', 1, ''),
('Question5', 1, ''),
('Question6', 1, ''),
('Question7', 1, ''),
('Question8', 1, ''),
('Question9', 1, ''),
('Question10', 1, ''),
('Question11', 1, ''),
('Question12', 1, ''),
('Question13', 1, '');

/* Ajout propositions questions forum */

INSERT INTO forumProposition(id_question, proposition)
VALUES(1, 'Proposition1'),
(1, 'Proposition2'),
(1, 'Proposition3'),
(1, 'Proposition4'),
(1, 'Proposition5'),
(2, 'Proposition1'),
(2, 'Proposition2'),
(2, 'Proposition3');