/*Destruction des tables*/

drop table if exists `admin`;
drop table if exists `professeur`;
drop table if exists `statistique`;
drop table if exists `etudiant`;
drop table if exists `questions`;
drop table if exists `sujets`;
drop table if exists `forumQuestion`;
drop table if exists `forumProposition`;

/* Création de la table utilisateur*/

create table `etudiant`(
	`id_etudiant` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_etudiant primary key (id_etudiant)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* Création de la table professeur */

create table `professeur`(
	`id_professeur` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_professeur primary key (id_professeur)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Creation de la table administrateur*/

create table admin(
    id_admin varchar(20) unique,
    password varchar(512),
    constraint pk_admin primary key (id_admin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

/* Création de la table statistique */

create table `statistique`(
    `id_statistique` int not null,
    `score` float,
    `id_subject` int not null
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*Creation de la table sujets */
create table sujets(
    id int auto_increment primary key,
    domaine varchar(50) not null,
    categorie varchar(50) not null,
    niveau varchar(50) not null
);

/*Creation de la table questions */

create table questions(
	id int auto_increment primary key,
    id_prof int not null,
    id_subject int not null,
    difficulte varchar(50) not null,
    question varchar(500) not null,
    code_reponses varchar(20) not null,
    reponseA varchar(250) not null,
    reponseB varchar(250) not null,
    reponseC varchar(250) not null,
    reponseD varchar(250) not null
);

/*Creation de la table forumQuestion */

create table forumQuestion(
    id int auto_increment primary key,
    question varchar(150) not null,
    id_student int not null,
    answer varchar(150)
);

/*Creation de la table forumProposition */

create table forumProposition(
    id_question int not null,
    proposition varchar(150) not null
);

/*Ajout Student*/
INSERT INTO etudiant(nom, prenom, email, telephone, password, adresse)
VALUES ('Student', 'Student', 'student@student.com', '0101010101', '2286db74888eee2de86d070c65fb9058486ac86e376f499da5fe90dae4d036fa026e7bbcb3a80f34adb7c38b2d3fe5153ed1dc302fd1776fe4b3bd0f9e4386f3', '1 rue des étudiants');

/*Ajout Prof*/
INSERT INTO professeur(nom, prenom, email, telephone, password, adresse)
VALUES ('Prof', 'Prof', 'prof@prof.com', '0202020202', 'b820e9862fa829c9af2ba64a64801097f4542590945b0ea539906e826950c5ba642a9b7d8a432b12f80aad8ad6428f6e7fe035d3e7f5ec5ce5564f5aa0d981ed', '1 rue des professeurs');

/*Ajout admin*/
INSERT INTO admin(id_admin, password)
VALUES ('admin', '5a38afb1a18d408e6cd367f9db91e2ab9bce834cdad3da24183cc174956c20ce35dd39c2bd36aae907111ae3d6ada353f7697a5f1a8fc567aae9e4ca41a9d19d');

/*Remplissage table sujets*/
INSERT INTO sujets(domaine, categorie, niveau)
values ('Mathematiques', 'Nombres', 'Primaire'),
('Mathematiques', 'Grandeurs', 'Primaire'),
('Mathematiques', 'Geometrie', 'Primaire'),
('Mathematiques', 'Statistiques', 'College'),
('Mathematiques', 'Geometrie', 'College'),
('Mathematiques', 'Algebre', 'College'),
('Mathematiques', 'Fonctions', 'Lycee'),
('Mathematiques', 'Suites', 'Lycee'),
('Mathematiques', 'Statistiques', 'Lycee'),
('Mathematiques', 'Algebre', 'Superieur'),
('Mathematiques', 'Analyse', 'Superieur'),
('Mathematiques', 'Probabilites', 'Superieur'),
('Physique', 'Electricite', 'College'),
('Physique', 'Lumiere', 'College'),
('Physique', 'Mecanique', 'College'),
('Physique', 'Electricite', 'Lycee'),
('Physique', 'Ondes', 'Lycee'),
('Physique', 'Optique', 'Lycee'),
('Physique', 'Mecanique', 'Lycee'),
('Physique', 'Mecanique', 'Superieur'),
('Physique', 'Electrocinetique', 'Superieur'),
('Physique', 'Thermodynamique', 'Superieur'),
('Chimie', 'Solutions aqueuses', 'College'),
('Chimie', 'Atomes', 'College'),
('Chimie', 'Atmosphere', 'College'),
('Chimie', '', 'Lycee'),
('Chimie', '', 'Superieur'),
('Biologie', '', 'College'),
('Biologie', '', 'Lycee'),
('Biologie', '', 'Superieur'),
('Geologie', '', 'College'),
('Geologie', '', 'Lycee'),
('Geologie', '', 'Superieur'),
('Informatique', '', 'College'),
('Informatique', 'Programmation', 'Lycee'),
('Informatique', '', 'Lycee'),
('Informatique', 'Programmation', 'Superieur'),
('Informatique', 'Reseaux', 'Superieur'),
('Informatique', 'S. d`exploitation', 'Superieur'),
('Histoire', 'Prehistoire', 'Primaire'),
('Histoire', 'Antiquite', 'Primaire'),
('Histoire', 'Moyen-Age', 'Primaire'),
('Histoire', 'Decouvertes', 'Primaire'),
('Histoire', '', 'Primaire'),
('Histoire', '', 'College'),
('Histoire', '', 'Lycee'),
('Histoire', '', 'Superieur'),
('Geographie', '', 'Primaire'),
('Geographie', '', 'College'),
('Geographie', '', 'Lycee'),
('Geographie', '', 'Superieur'),
('Francais', 'Conjugaison', 'Primaire'),
('Francais', '', 'Primaire'),
('Francais', '', 'College'),
('Francais', '', 'Lycee'),
('Francais', '', 'Superieur'),
('Anglais', '', 'Primaire'),
('Anglais', '', 'College'),
('Anglais', '', 'Lycee'),
('Anglais', '', 'Superieur');


/*Remplissage table questions*/

INSERT INTO questions (id_prof, id_subject, difficulte, question, code_reponses, reponseA, reponseB, reponseC, reponseD)
values (1, 1, 'Facile', '15 + 48 = ?', '010', '54', '63', '36', ''),
(1, 1, 'Facile', '48 - 15 = ?', '001', '23', '32', '33', ''),
(1, 1, 'Facile', '3 x 9 = ?', '001', '18', '36', '27', ''),
(1, 1, 'Facile', '45 / 9 = ?', '01', '4', '5', '', ''),
(1, 1, 'Facile', '15 + 450 = ?', '0100', '455', '465', '15450', '4515'),
(1, 1, 'Facile', '220 - 85 = ?', '1000', '135', '153', '165', '156'),
(1, 1, 'Facile', '7 x 3 = ?', '0010', '28', '14', '21', '35'),
(1, 1, 'Moyen', '56 / 8 = ?', '0001', '5', '6', '9', '7'),
(1, 1, 'Facile', '44 + ... = 78', '010', '25', '34', '38', ''),
(1, 1, 'Moyen', '890 - ... = 148', '001', '756', '648', '742', ''),
(1, 2, 'Facile', '16 cm = ?', '0011', '16 m', '1,6 m', '0,16 m', '160 mm'),
(1, 2, 'Facile', '42 km = ?', '0101', '420 m', '42000 m', '42 cm', '4200000 cm'),
(1, 2, 'Facile', '25 L = ?', '0100', '25 cL', '250 dL', '25000 cL', '2,5 hL'),
(1, 2, 'Facile', '30 mn = ?', '0010', '300 s', '1000 s', '1800 s', '180 s'),
(1, 2, 'Facile', 'Vrai ou Faux : 150 min = 2h30', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 300 ms = 3 s', '01', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 360 s = 6 mn', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 4000 mL = 400 cL', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Facile', 'Comment se nomme une figure à 3 côtés ?', '010', 'Un cercle', 'Un triangle', 'Un carré', ''),
(1, 3, 'Facile', 'Comment appele-t-on la famille des figures à 4 côtés ?', '01', 'Les pentagones', 'Les quadrilatères', '', ''),
(1, 3, 'Facile', 'Quelle figure ne fait pas partie des quadrilatères ?', '0100', 'Le carré', 'Le pentagone', 'Le rectangle', 'Le losange'),
(1, 3, 'Moyen', 'Comment calculer le périmètre des carrés ?', '110', 'P = c * 4', 'P = (L + l) x 2', 'P = c x c', ''),
(1, 3, 'Moyen', 'Comment calculer le périmètre du cercle ?', '001', 'P = pi x r²', 'P = pi x r', 'P = pi x 2r', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle droit vaut 90°', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle obtus est inférieur à 90°', '01', 'Vrai', 'Faux', '', ''),
(1, 4, 'Moyen', 'Quelle est la moyenne des nombres suivants : 12 18 ?', '0100', '14', '15', '16', '17'),
(1, 4, 'Facile', 'Quelle est la médiane des nombres : 13 15 18', '010', '16', '15', '15.33', ''),
(1, 4, 'Facile', 'Quelle est la moyenne des nombres : 7 15 20', '0010', '15', '16', '14', '17'),
(1, 4, 'Facile', 'Quel est le premier quartile ? : 5 10 15 14', '0100', '10', '5', '14', '15'),
(1, 4, 'Facile', '5 boules rouges et 2 boules noires. Probabilité de tirer une boule noire ?', '100', '2/7', '1/7', '5/7', ''),
(1, 4, 'Facile', '3 boules vertes, 2 boules bleues, 1 boule rouge. Probabilité de tirer 2 boules vertes ?', '0100', '2/6', '1/30', '1/11', '1/6'),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant à : 15/20', '010', '60%', '75%', '80%', ''),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant à : 48/50', '01', '48%', '96%', '', ''),
(1, 4, 'Facile', 'Quelle est la fréquence correpondant à : 4 élèves sur 8', '010', '25%', '50%', '75%', ''),
(1, 4, 'Facile', 'Quelle est la fréquence correspondant à : 8 français sur 10', '0010', '8%', '40%', '80%', '90%'),
(1, 5, 'Facile', 'Quelle est l`hypothénuse d`un triangle rectangle', '01', 'Le côté le plus court', 'Le côté le plus long', '', ''),
(1, 5, 'Facile', 'Vrai ou Faux : On peut parler de la médiatrice d`une droite', '01', 'Vrai', 'Faux', '', ''),
(1, 5, 'Facile', 'Quelle est la définition de la bissectrice', '010', 'La droite perpendiculaire coupant un segment en deux parts égales', 'La droite coupant un angle en deux parts égales', 'La droite passant par le cente d`un segment', ''),
(1, 5, 'Facile', 'Comment calculer l`aire d`un carré ?', '001', 'A = 4 x c', 'A = c + c', 'A = c x c', ''),
(1, 5, 'Facile', 'Comment calculer le volume d`un parallélépipède rectangle', '010', 'V = l + L + h', 'V = l * L * h', 'V = l * L / h', ''),
(1, 5, 'Facile', 'Comment écrire "la droite AB"', '0100', '[AB]', '(AB)', '[AB)', '(AB]'),
(1, 5, 'Facile', 'Quel est le théorème de Pythagore ?', '0100', 'AB² = AC² = BC²', 'AB² + BC² = AC²', 'AB² - BC² = AC²', 'BC² + BA² = 2AC'),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle isocèle ?', '01', 'Un triangle a 3 côtés égaux', 'Un triangle à deux côtés égaux', '', ''),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle rectangle', '0010', 'Un quadrilatère', 'Un triangle quelconque', 'Un triangle avec un angle droit', 'Un triangle à 3 côtés égaux'),
(1, 6, 'Facile', '3x + 15 = 12. x = ?', '0001', '-2', '2', '1', '-1'),
(1, 6, 'Facile', '12 - x = -2. x = ?', '0100', '10', '14', '16', '-10'),
(1, 6, 'Facile', '9x + 9 = 0. x = ?', '1000', '-1', '1', '10', '-10'),
(1, 6, 'Facile', '4x + 5 = x + 2. x = ?', '0010', '1', '3', '-1', '-3'),
(1, 6, 'Facile', '5x + 4 = 2x + 1. x = ?', '0100', '1', '-1', '3', '-3'),
(1, 6, 'Facile', '10x + 5 = 15x. x = ?', '0001', '10', '-1', '3', '1'),
(1, 7, 'Facile', 'Soit f(x) = 3x + 15. Que vaut f(5) ?', '0010', '60', '23', '30', '35'),
(1, 7, 'Facile', 'Soit f(x) = 14x + 12. Quelle est l`ordonnée à l`origine', '100', '12', '14', '26', ''),
(1, 7, 'Facile', 'Soit f(x) = x² + 2x + 1. Factoriser', '0100', 'x(x + 2) + 1', '(x + 1)²', '(x + 1)(x - 1)', '(x - 1)²'),
(1, 7, 'Facile', 'Soit f(x) = 4x² + 6x + 15. Dériver', '001', '4x + 6', '2x + 6', '8x + 6', ''),
(1, 7, 'Facile', 'Soit f(x) = 4x. Donner une primitive', '0001', 'x + constante', '4', '2x', '2x² + constante'),
(1, 7, 'Facile', 'Soit f(x) = 2x + 1. Sur quel intervalle est-elle positive ?', '0010', '[0; +inf[', '[1; +inf[', '[-1; +inf[', '[-1; +inf]'),
(1, 7, 'Facile', 'Soit f(x) = x². En quelle valeur s`annule-t-elle ?', '01', '1', '0', '', ''),
(1, 7, 'Facile', 'Soit f(x) = -x² + 3x. Sur quel intervalle est-elle croissante ?', '01', ']-inf; 1.5]', '[1.5; +inf[', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 4. u est-elle une suite géométrique ?', '01', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 4. u est-elle une suite géométrique ?', '10', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_0 = 1 et u_n+1 = u_n * 4. Que vaut u_4 ?', '0010', '16', '8', '64', '128'),
(1, 8, 'Facile', 'Quelle est la suite arithmético-géométrique', '010', 'u_n+1 = u_n + a', 'u_n+1 = u_n * q + a', 'u_n+1 = u_n * q', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 16 et u_0 = 10. Quelle est la raison de u ?', '01', '10', '16', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 15 et u_0 = 12. Quelle est la raison de u ?', '10', '15', '12', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+2 = u_n+1 + u_n, u_0 = 0 et u_1 = 1. Que vaut u_4 ?', '0100', '2', '3', '4', '5'),
(1, 8, 'Facile', 'Soit u telle que u_0 = 10 et u_n+1 = u_n. Que vaut u_100 ?', '0100', '10 000', '10', '1000', '1000'),
(1, 9, 'Facile', 'Quel est l`ensemble des résultats d`un dé non pipé ?', '0010', '{0, 1, 2, 3}', '{1, 3, 5}', '{1, 2, 3, 4, 5, 6}', '{2, 4, 6}'),
(1, 9, 'Facile', 'Soient A et B deux évènements. Que signifie A u B ?', '010', 'A inter B', 'A union B', 'A privé de B', ''),
(1, 9, 'Facile', 'Soient A et B deux évènements. Quelle est la probabilité conditionnelle ?', '0001', 'P(A u B)', 'P(A n B)', 'P(A \ B)', 'P_A(B)'),
(1, 9, 'Facile', 'Soient A et B deux évèenements. A n B signifie A inter B.', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Le cardinal d`un ensemble est le nombre d`éléments de cet ensemble', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Soit A un évènement. Quelle est la probabilité de son évènement opposé ?', '1000', '1 - P(A)', 'P(A) - 1', '1 / P(A)', '-P(A)'),
(1, 9, 'Facile', 'On lance 10 fois un dé non pipé. Quelle loi utiliser pour cette étude ?', '01', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'On lance une fois un dé non pipé. Quelle loi utiliser pour cette étude ?', '10', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Une variable aléaoire n`associe par toujours une issure à un réel', '01', 'Vrai', 'Faux', '', ''),
(1, 10, 'Facile', 'Que vaut cos(0) ?', '010', '0', '1', 'π', ''),
(1, 10, 'Facile', 'Quelle proposition est fausse ?', '0100', 'sin(πθ) = π sin(θ)', 'cos²(x) - sin²(x) = 1', 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)', 'sin(a + b) = sin(a)cos(b) + sin(b)cos(a)'),
(1, 10, 'Facile', 'Que vaut sin(π/6) ?', '01', '√3 / 2', '1 / 2', '', ''),
(1, 10, 'Facile', 'Quel est le théorème de Bézout ?', '01', 'Soient a, b, c, si a divise bc et PGCD(a;b) = 1, alors a divise c', 'Soient a, b; si PGCD(a,b)=1 alors il existe u,v tq au + bv = 1', '', ''),
(1, 10, 'Facile', 'Qu`est ce que la congruence entre deux nombres a et b ?', '010', 'Lorsqu`il existe q tel que a = bq', 'Lorsqu`il existe k tel que a - b = kn', 'Lorsqu`il existe (q, r) tel que a = bq + r', ''),
(1, 10, 'Facile', 'Comment s`écrit l`ensemble des racines n-ième de l`unité ?', '010', 'Q', 'U_n', 'UN', ''),
(1, 10, 'Facile', 'Quelle est la notation d`une racine n-ième de l`unité ?', '1000', 'exp(i * 2 * k * π / n) avec k dans [0, n - 1]', 'exp(iπ/n)', 'exp(ik/n) avec k dans [0, n - 1]', 'exp(i * k * π / n) avec k dans [0, n - 1]'),
(1, 10, 'Facile', 'Quelle est la notation exponentielle d`un nombre complexe ?', '0010', 'exp(i) = cos(iθ)', 'exp(θ) = cos(i) + sin(i)', 'exp(iθ) = cos(θ) + i*sin(θ)', 'exp(iθ) = cos(θ) - i*sin(θ)'),
(1, 10, 'Facile', 'Comment s`écrit un nombre complexe ?', '0011', 'z = i', 'z = xi', 'z = xi + y', 'z = xi - y'),
(1, 11, 'Facile', 'Vrai ou Faux : (g o f)` = g` x (f` o g)', '01', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Vrai ou Faux : (fg)`= f`g + fg`', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Soit f une fonction continue et strictement monotone sur I, alors : ', '001', 'f réalise une injection de I sur J = f(I)', 'f réalise une surjection de I sur J = f(I)', 'f réalise une bijection de I sur J = f(I)', ''),
(1, 11, 'Facile', 'Quand dit-on qu`une fonction f est continue en a ?', '0010', 'Lorsqu`elle est dérivable en a', 'Lorsque la limite en a est non nulle', 'Lorsque la limite en a vaut f(a)', 'Lorsque f s`annule en a'),
(1, 11, 'Facile', 'Si f(x) <= g(x) <= h(x) et si f et h admettent une limite l en a, alors g admet une limite l en a', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Peut-il y avoir plusieurs limites pour une même valeur a ?', '01', 'Oui', 'Non', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en -inf de exp ?', '10', '0', '+inf', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en 0 de ln ?', '0100', '0', '-inf', '+inf', 'e'),
(1, 11, 'Facile', 'Qu`est ce qu`une fonction dite CADLAG ?', '010', 'Cosinus à droite, Logarithme à gauche', 'Continue à droite, Limite à gauche', 'Croissante à droite, linéaire à gauche', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(A u B) = Card(A) + Card(B)', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Si A et B sont disjoints, Card(A u B) = Card(A) + Card(B)', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(E x F) = Card(E) x Card(F) oÃ¹ E et F sont deux ensembles', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Une variable aléatoire réelle est une inconnue telle que x', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Quand dit-on que deux évènements sont indépendants ?', '010', 'Lorsque P(A u B) = P(A)P(B)', 'Lorsque P(A n B) = P(A)P(B)', 'Lorsque P(A u B) = P(A) + P(B)', ''),
(1, 12, 'Facile', 'Quand dit-on que deux évènements sont incompatibles ?', '0100', 'Lorsque P(A n B) = A', 'Lorsque P(A u B) = P(A) + P(B)', 'Lorsque P(A u B) = P(A)', 'Lorsque P(A) = P(B)'),
(1, 12, 'Facile', 'Quelle est la formule de Pascal ?', '0001', 'nCp = (n-1)Cp', 'nCp = (n+1)C(p+1)', 'nC(p-1) = (p+1)C(n-1)', 'nCp = (n-1)Cp + (n-1)C(p-1)'),
(1, 13, 'Facile', 'Quelle loi s`applique pour l`intensité du courant dans un circuit en série ?', '01', 'La loi d`additivité', 'La loi d`unicité', '', ''),
(1, 13, 'Facile', 'Qu`est ce que la loi d`additivité d`intensité ?', '0100', 'L`intensité d`une branche dérivée est égale aux autres', 'L`intensité de la branche principale vaut la somme des dérivées', 'L`intensité d`une branche dérivée vaut la somme des autres', 'L`intensité est la même dans tout le circuit'),
(1, 13, 'Facile', 'Qu`est ce qu`un dipôle ?', '01', 'Un composant magnétique avec deux pôles', 'Un composant électrique avec deux bornes', '', ''),
(1, 13, 'Facile', 'Quand applique-t-on la loi d`additivité de la tension ?', '10', 'Un circuit en série', 'Un circuit en dérivation', '', ''),
(1, 13, 'Facile', 'Quelle est la loi d`Ohm ?', '0110', 'R = U x I', 'U = R x I', 'I = U / R', 'I = U x R'),
(1, 13, 'Facile', 'Comment mesure-t-on une intensité ?', '0001', 'Un voltmètre en dérivation', 'Un voltmètre en série', 'Un ampèremètre en dérivation', 'Un ampèremètre en série'),
(1, 13, 'Facile', 'Quelle est l`unité de l`intensité ?', '1000', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 13, 'Facile', 'Comment calcule-t-on la puissance électrique ?', '0010', 'P = U x R', 'P = U / I', 'P = U x I', 'U = P x I'),
(1, 13, 'Facile', 'Quelle est l`unité de la puissance électrique ?', '0001', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 13, 'Facile', 'Comment déterminer la valeur d`une résistance ?', '0110', 'En la branchant en série avec une intensité électrique prédéfinie', 'En regardant son code couleur', 'En utilisant un ohmmètre à l`extérieur du circuit', 'En utilisant un ohmmètre à l`intérieur du circuit'),
(1, 13, 'Facile', 'Quelle est l`unité de la tension ?', '0100', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 13, 'Facile', 'Quel est l`inventeur de l`électricité ?', '0100', 'Thomas Edison', 'Maxwell', 'Edward Ferrara', 'Aucune de ces personnes'),
(1, 13, 'Facile', 'Quel est l`inventeur de la lampe à incandescence ?', '1000', 'Thomas Edison', 'Louis Pasteur', 'Isaac Newton', 'Graham Bell'),
(1, 14, 'Facile', 'Sources de lumière : Quel est l`intrus ?', '001', 'Les sources primaires', 'Les objets diffusants', 'Les objets réflechissants', ''),
(1, 14, 'Facile', 'La trajectoire de la lumière est un mouvement ...', '0100', 'Circulaire', 'Rectiligne', 'Parabolique', 'SinusoÃ¯dal'),
(1, 14, 'Facile', 'Quelles sont les couleurs qui composent la lumière ?', '0100', 'Rouge Bleu Jaune', 'Toutes les couleurs de Violet à Rouge', 'Rouge Vert Bleu', 'Magenta Jaune Cyan'),
(1, 14, 'Facile', 'A quoi est dûe la couleur d`un objet', '1100', 'Aux pigments présents sur l`objet', 'A la lumière éclairant l`objet', 'A la lumière que l`objet absorbe' , 'Au rayonnement naturel de l`objet'),
(1, 14, 'Facile', 'Quel comportement a la lumière avec une lentille convergente ?', '10', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quel comportement a la lumière avec une lentille divergente ?', '01', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quelle est la vitesse de la lumière ?', '0010', '300 km/s', '3 000 m/s', '300 000 km/s', '300 000 m/s'),
(1, 14, 'Facile', 'Vrai ou Faux : Un oeil est comparable à une lentille avec un écran', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La lumière a la même vitesse quelque soit le milieu', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Magenta Jaune et Cyan sont les composantes principales de la lumière', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Utiliser deux couleurs de lumière permet d`en obtenir une autre', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La vitesse de la lumière sert à mesurer des distances spatiales', '10', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Interactions : Quel est l`intrus ?', '001', 'L`interaction magnétique', 'L`interaction gravitationnelle', 'L`interaction mécanique', ''),
(1, 15, 'Facile', 'Qu`est ce que le poids d`un objet ?', '01', 'La quantité de matière d`un objet', 'L`action gravitationnelle exercée sur cet objet', '', ''),
(1, 15, 'Facile', 'Qu`est ce que la masse d`un objet ?', '10', 'La quantité de matière d`un objet', 'L`action gravitationnelle exercée sur cet objet', '', ''),
(1, 15, 'Facile', 'Quelle est la relation entre le poids et la masse ?', '0010', 'P = m / g', 'm = P x g', 'P = m x g', 'g = m x P'),
(1, 15, 'Facile', 'Qu`est ce que l`énergie ?', '010', 'Une quantité de mouvement', 'La capacité d`un objet à agir sur lui même et les autres', 'Une quantité de température', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie de position ?', '10', 'Une énergie dépendant de la hauteur', 'Une énergie dépendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie cinétique ?', '01', 'Une énergie dépendant de la hauteur', 'Une énergie dépendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie mécanique ?', '01', 'Un terme général pour parler de l`énergie, cinétique ou de position', 'La comme de l`énergie cinétique et de l`énergie de position', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la formule de l`énergie cinétique est m x v²', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la masse n`influe pas sur l`énergie cinétique', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la vitesse influe sur l`énergie cinétique', '10', 'Vrai', 'Faux', '', ''),
(1, 16, 'Facile', 'Qu`est ce qu`un noeud ?', '010', 'Un dipôle', 'Un point de connexion entre au moins 3 dipôles', 'Une partie de circuit', ''),
(1, 16, 'Facile', 'Qu`est ce qu`une maille  ?', '001', 'Un dipôle', 'Une partie de circuit', 'Une boucle fermée', ''),
(1, 16, 'Facile', 'Quelle est la loi des noeuds ?', '10', 'Somme des intensités entrantes = Somme des intensités sortantes', 'Somme des tensions entrantes = Somme des tensions sortantes', '', ''),
(1, 16, 'Facile', 'Quelle est la loi des mailles ?', '01', 'La somme des intensités dans une maille est nulle', 'La somme des tensions dans une maille est nulle', '', ''),
(1, 16, 'Facile', 'Comment représente t on la caractéristique d`un dipôle', '01', 'Un graphe Volt en x Ampère en y', 'Un graphe Ampère en x Volt en y', '', ''),
(1, 17, 'Facile', 'Qu`est ce qu`une onde mécanique ?', '0110', 'Un onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matière', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Qu`est ce qu`une onde électromagnétique', '1001', 'Une onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matière', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Quel est le symbôle de la fréquence d`une onde sonore', '01', 'f (fréquence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Quel est l`unité de la fréquence d`une onde sonore', '10', 'f (fréquence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : l`intensité sonore est exprimée en Watt', '01', 'Vrai', 'Faux', '', ''), 
(1, 17, 'Facile', 'Vrai ou Faux : une onde est doublement périodique', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Lors de la propagation d`une onde il y a déplacement de matière', '01', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Une onde est un transport d`énergie', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Quand dit on qu`une onde mécanique est progressive', '010', 'Lorsqu`elle accélère progressivement', 'Lorsqu`elle se propage de proche en proche', 'Lorsqu`elle ralentit progressivement', ''),
(1, 17, 'Facile', 'Pour parler de la vitesse de propragation d`une onde on parle de ...', '01', 'Vitesse', 'Célérité', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', 'Quelle est la constante de Planck ?', '0100', 'h = 8,026 080 15 × 10−17 J s', 'h = 6,626 070 15 × 10−34 J s', 'h = 0,626 070 15 × 10−34 J s', 'h = 8,026 081 15 × 10−19 J s'),
(1, 20, 'Facile', 'Lorsque je mets une balle au sol, son énergie mécanique est égale à ?', '1000', 'Energie mécanique = Energie cinétique', 'Energie mécanique = 0', 'Energie mécanique = Energie potentielle', 'Energie mécanique = Energie cinétique x Energie potentielle'),
(1, 20, 'Facile', 'Dans la célèbre formule e=mc², quelle est la nature de c ?', '0001', 'L`énergie emmagasinée', 'La concentration du molécule', 'La masse', 'La vitesse de la lumière'),
(1, 20, 'Facile', 'Qu`appelle-t-on un trou noir ?', '01', 'Tourbillon célest au niveau duquel la matière ne peut s`échapper', 'Objet céleste si compact que rien ne peut s`échapper de son champ gravitationnel', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile','Comment caractérise-t-on la gravitation universelle ', '0001', 'C`est une interaction attractive de contact.', 'C`est une interaction répulsive à distance.', 'C`est une interaction répulsive de contact.', 'C`est une interaction attractive à distance.'),
(1, 26, 'Facile', ' La puissance nominale d`un appareil.', '0010', 'Est la puissance liée à son nom.', 'Est la puissance que l`appareil peut fournir.', 'Est la puissance que l`appareil peut recevoir.', 'Est la même pour tous les appareils électriques.'),
(1, 26, 'Facile', 'La puissance électrique est une grandeur physique qui s`exprime en...', '0010', 'Volts (V)', 'Ampères (A)', 'Watts (W)', 'Joules (J)'),
(1, 26, 'Facile', ' Lorsqu`un appareil est alimenté par une tension sinusoïdale, U et I :', '1000', 'Correspondent à leur grandeur efficace  et .', 'Restent identiques à leurs valeurs en tension continue.', 'Sont plus efficaces.', 'Ne varient jamais.'),
(1, 26, 'Facile', 'La puissance nominale d`un appareil...', '0010', 'Est la puissance liée à son nom.', 'Est la puissance que l`appareil peut fournir.', 'Est la puissance que l`appareil peut recevoir.', 'Est la même pour tous les appareils électriques.'),
(1, 26, 'Facile', 'Quelle relation permet de calculer l`interaction gravitationnelle appliquée à un objet au voisinage de la Terre ?.', '1000', 'P = m x g', 'E = P x t', 'F=G×mA×mB/r2', 'D = v x t'),
(1, 26, 'Facile', 'Par quoi sont modélisées les interactions ?', '1000', 'C`est une interaction attractive de contact.', 'C`est une interaction répulsive à distance.', 'C`est une interaction répulsive de contact.', 'C`est une interaction attractive à distance.'),
(1, 26, 'Facile', ' Comment un atome est-il chargé ?', '0010', 'Positivement', 'Négativement', 'Électriquement neutre', 'Avec un pôle nord et un pôle sud'),
(1, 26, 'Facile', 'Que représente le numéro atomique Z d`un atome ?', '0100', 'Le nombre d`électrons (charges négatives)', 'Le nombre de protons (charges positives)', 'Le nombre de neutrons (particules non chargées)', 'Le nombre de nucléons'),
(1, 26, 'Facile', ' Qu`est-ce qu`un ion ?', '1000', 'Un atome qui gagne ou perd des électrons.', 'Un atome qui gagne ou perd des protons.', 'Un atome qui gagne ou perd des neutrons.', 'Plusieurs atomes qui s`associent entre eux.'),
(1, 26, 'Facile', 'Quelles sont les deux parties qui composent un atome ?', '1000', 'Le noyau', 'Les électrons', 'Les protons', 'Les neutrons'),
(1, 26, 'Facile', ' Comment sont chargés les électrons ?', '0200', 'Positivement', 'Négativement', 'Ils ne sont pas chargés.', 'Ils ont une partie positive et une autre négative.'),
(1, 26, 'Facile', 'De quelles grandeurs physiques dépend l`énergie de position (Ep) ?', '1100', 'Masse', 'Hauteur', 'Vitesse', 'Température'),
(1, 26, 'Facile', ' De quelles grandeurs physiques dépend l`énergie cinétique (Ec) ?', '1010', 'Masse', 'Hauteur', 'Vitesse', 'Température'),
(1, 26, 'Facile', 'Que se passe-t-il pour les énergies de position, cinétique et mécanique lors de la chute d`un objet ?', '0001', 'L`énergie de position augmente, l`énergie cinétique diminue et l`énergie mécanique reste constante.', 'L`énergie de position reste constante, l`énergie cinétique augmente et l`énergie mécanique diminue.', 'L`énergie de position diminue, l`énergie cinétique reste constante et l`énergie mécanique augmente.', 'L`énergie de position diminue, l`énergie cinétique augmente et l`énergie mécanique reste constante.'),
(1, 26, 'Facile', ' Quel type d`espèce chimique est produit lors de la réaction entre un acide et un métal ?', '1000', 'Un gaz', 'Un liquide', 'Un solide', 'Un précipité'),
(1, 26, 'Facile', 'Par quel test peut-on mettre en évidence le gaz formé par la réaction entre un acide et un métal ', '0001', 'On approche un papier, imbibé de rouge de crésol, du dégagement gazeux et celui-ci devient jaune.', 'En faisant barboter le gaz dans de l`eau de chaux', 'En approchant une allumette encore incandescente, la flamme se ravive.', 'n approchant une allumette enflammée, une détonation se produit.'),
(1, 26, 'Facile', ' Lors de la réaction entre un acide et une base, quel type d`espèce chimique se forme avec le gaz ?', '1000', 'Des ions', 'Un autre gaz', 'Un solide', 'Un liquide incolore'),
(1, 26, 'Facile', 'Si l`on fait réagir du fer et de l`acide chlorhydrique et que se produisent des ions Fe2+ et du dihydrogène, quels sont les produits ?', '0011', 'Fer', 'Acide chlorhydrique', 'Ions Fe2+', 'Dihydrogène'),
(1, 26, 'Facile', ' Si l`on fait réagir du fer et de l`acide chlorhydrique et que se produisent des ions Fe2+ et du dihdrogène, quels sont les réactifs ?', '1100', 'Fer', 'Acide chlorhydrique', 'Ions Fe2+', 'Dihydrogène'),
(1, 26, 'Facile', 'Quel scientifique a dit : « Rien ne se perd, rien ne se crée, tout se transforme. » ?', '0001','Einstein', 'Newton', 'Volta', 'Lavoisier'),
(1, 26, 'Facile', ' Quels sont les éléments qui doivent être conservés lors d`une transformation chimique ', '1100', 'Le nombre d`atomes', 'La charge globale', 'Les molécules', 'Les ions'),
(1, 26, 'Facile', 'Comment appelle-t-on le numéro devant les atomes, les molécules ou les ions dans une transformation chimique ', '0010', 'Le nombre de masse', 'Le numéro atomique', 'Le coefficient stœchiométrique', 'Le nombre d`or'),
(1, 26, 'Facile', ' Lors de la réaction du carbone avec le dioxygène, du dioxyde de carbone est produit. Comment s`écrit l`équation chimique équilibrée ', '1000', 'C + O2 --> CO2', 'CO2 --> C + O2', 'C + O + O --> CO2', 'CO + O --> CO2'),
(1, 26, 'Facile', 'Comment appelle-t-on les espèces chimiques qui ne réagissent pas dans une réaction chimique ?', '0001', 'Ce sont des espèces chimiques fluorescentes.', 'Ce sont des espèces chimiques radioactives.', 'Ce sont des espèces chimiques volatiles.', 'Ce sont des espèces chimiques inertes ou spectatrices.'),
(1, 26, 'Facile', ' Quel type d`énergie est stocké dans une pile ?', '0100', 'Énergie thermique', 'Énergie chimique', 'Énergie électrique', 'Énergie cinétique'),
(1, 26, 'Facile', 'Quel type d`énergie est produit par une pile ?', '0010', 'Énergie thermique', 'Énergie chimique', 'Énergie électrique', 'Énergie cinétique'),
(1, 26, 'Facile', ' Comment se nomment les particules échangées entre les réactifs d`une pile et qui permettent la création d`un courant électrique ', '0010', 'Les protons', 'Les neutrons', 'Les électrons', 'Les nucléons'),
(1, 26, 'Facile', 'Quelle conversion d`énergie se produit-il dans le cas d`une électrolyse ?', '0001', 'De l`énergie chimique est convertie en énergie électrique.', 'De l`énergie thermique est convertie en énergie électrique.', 'De l`énergie thermique est convertie en énergie électrique.', 'De l`énergie électrique est convertie en énergie chimique.'),
(1, 26, 'Facile', ' Comment se nomment les deux côtés d`une pile ?', '1000', 'Les électrodes', 'Les pôles', 'Les ponts', 'Les nœuds'),
(1, 26, 'Facile', 'Quels sont les ions que l`atome de fer (symbole Fe) peut former ?', '1100', 'Fe2+', 'Fe3+', 'Cu2+', 'Cl-'),
(1, 26, 'Facile', ' Quel réactif permet de mettre en évidence les ions Fe2+, Fe3+, Cu2+ et Zn2+', '0100', 'Nitrate d`argent', 'Soude', 'Chlorure de baryum', 'Chlorure de sodium'),
(1, 26, 'Facile', 'Quel type d`espèce chimique se forme lors d`un test des ions ?', '0100', 'Du gaz', 'Un précipité', 'Un liquide incolore', 'Des ions'),
(1, 26, 'Facile', ' Lorsque le pH est inférieur à 7, on dit que la solution est acide, quels ions sont alors majoritairement présents en solution ?', '1000', 'Ions hydrogène H+', 'Ions hydroxyde HO-', 'Ions chlorure Cl-', 'Ions cuivre II Cu2+'),
(1, 26, 'Facile', 'Lorsque le pH est supérieur à 7, on dit que la solution est basique, quels ions sont alors majoritairement présents en solution ?', '0100', 'Ions hydrogène H+', 'Ions hydroxyde HO-', 'Ions chlorure Cl-', 'Ions cuivre II Cu2+'),
(1, 26, 'Facile', ' Comment appelle-t-on le passage d`une forme d`énergie à une autre ?', '1000', 'Une conversion d`énergie', 'Un transfert d`énergie', 'Une perte d`énergie', 'Un bilan énergétique'),
(1, 26, 'Facile', 'Comment appelle-t-on le passage de l`énergie d`un corps à un autre ?', '1000', 'Une conversion d`énergie', 'Un transfert d`énergie', 'Une perte d`énergie', 'Un bilan énergétique'),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', 'Lors d`un effort, notre corps utilise de l`énergie apportée par : ?', '1101', 'Les aliments', 'Les nutriments', 'Le CO2', 'Le dioxygène'),
(1, 28, 'Facile', 'Lors d`un effort, la fréquence cardiaque maximale peut atteindre : ?', '0010', '80 battements/minute', '100 battements/minute', '200 battements/minute', '300 battements/minute'),
(1, 28, 'Facile', 'Lors d`un effort, la consommation de dioxygène peut atteindre : ?', '0010', '1 L/minute', '2 L/minute', '3 L/minute', '4 L/minute'),
(1, 28, 'Facile', ' Notre fréquence cardiaque est contrôlée par : ?', '101', 'Le nerf sympathique qui accèlère la fréquence cardiaque.', 'Le nerf parasympathique qui accèlère la fréquence cardiaque', 'Le nerf parasympathique qui ralentit la fréquence cardiaque', ''),
(1, 28, 'Facile', 'La pratique d`un sport : ?', '0110', 'Ne nécessite pas une visite médicale obligatoire.', 'Nécessite une vérification de la fréquence cardiaque par le médecin', 'Dépend de l`âge, du sexe, de la masse du sportif.', 'Nécessite obligatoirement l`accord du médecin.'),
(1, 28, 'Facile', 'Le système nerveux comprend : ?', '1011', 'Le cerveau', 'L`intestin', 'Le système nerveux pépriphérique', 'La moelle épinière'),
(1, 28, 'Facile', 'Le cerveau : ?', '1010', 'Est relié aux organes effecteurs.', 'N`est pas relié aux organes sensoriels.', 'Régule les mouvements.', 'Ne régule pas la pensée.'),
(1, 28, 'Facile', 'Les neurones : ?', '0101', 'Sont plusieurs millions dans le cerveau.', 'Sont plusieurs milliards dans le cerveau.', 'Ne sont pas reliés entre eux.', 'Fabriquent des neurotransmetteurs.'),
(1, 28, 'Facile', 'Est-ce faux ?', '0010', 'Un électroencéphalogramme plat indique la mort cérébrale.', 'Le scanner permet de cartographier le cerveau.', 'L`IRM n`est pas une technique d`imagerie médicale.', 'La tomographie permet d`étudier l`activité cérébrale.'),
(1, 28, 'Facile', 'Le sommeil : ?', '0111', 'Se compose de 9-10 cycles de trente minutes.', 'Se compose de 4-5 cycles d`une heure et trente minutes environ.', 'Peut être lent ou paradoxal.', 'A des conséquences sur les performances intellectuelles.'),
(1, 28, 'Facile', 'La digestion : ?', '1010', 'S`effectue dans le tube digestif.', 'Consiste à transformer les aliments en grosses molécules.', 'Nécessite l`action de glandes digestives.', 'Ne s`effectue pas grâce aux enzymes.'),
(1, 28, 'Facile', 'L`absorption intestinale : ?', '100', 'Fait passer les nutriments dans notre milieu intérieur.', 'Ne se fait pas dans l`intestin grêle.', 'Se fait uniquement dans le gros intestin.', ''),
(1, 28, 'Facile', 'Cela fait partie du tube digestif : ?', '101', 'L`estomac', 'La trachée', 'L`œsophage', ''),
(1, 28, 'Facile', 'Est-ce faux : ?', '0001', 'La salive et l`intestin contiennent de l`amylase.', 'L`intestin contient de la maltase.', 'Le suc gastrique contient une protease.', 'La bile du foie n`agit pas sur les lipides.'),
(1, 28, 'Facile', 'Les bactéries : ?', '011', 'Sont apparues il y a deux milliards d`années.', 'Sont présentes dans l`eau.', 'Sont présentes dans notre corps.', ''),
(1, 28, 'Facile', ' Une bactérie :?', '0101', 'Est constituée de nombreuses cellules.', 'Est un procaryote.', 'Possède un noyau.', 'Possède un chromosome circulaire.'),
(1, 28, 'Facile', 'Les bactéries pathogènes : ?', '0101', 'Sont inoffensives.', 'Peuvent nous contaminer par contact avec la peau.', 'Ne peuvent pas provoquer d`infection.', 'Peuvent se trouver dans le sang.'),
(1, 28, 'Facile', 'Le système immunitaire : ?', '001', 'Est assuré par toutes les cellules de notre organisme.', 'Est assuré par les globules rouges.', 'Est assuré par les globules blancs.', ''),
(1, 28, 'Facile', 'Il y a : ?', '010', 'Un seul type de réaction immunitaire', 'Deux types de réactions immunitaires', 'Trois types de réactions immunitaires', ''),
(1, 28, 'Facile', 'La phagocytose : ?', '0101', 'Fait intervenir tous les types de globules blancs.', 'Fait intervenir des globules blancs appelés phagocytes.', 'Est la deuxième réaction immunitaire de notre corps.', 'Est la première réaction immunitaire de notre corps.'),
(1, 28, 'Facile', 'Est-ce faux ? ?', '0110', 'La phagocytose digère les bactéries.', 'Les lymphocytes T produisent les anticorps.', 'Les lymphocytes B ne produisent pas les anticorps.', 'La seconde réaction immunitaire fait intervenir les lymphocytes T et B.'),
(1, 28, 'Facile', 'La vaccination : ?', '1011', 'Consiste à injecter un antigène dans le corps.', 'Nécessite une seule injection dans sa vie.', 'Fait intervenir la mémoire immunitaire.', 'Augmente l`efficacité de la réaction immunitaire lors de la 2e infection avec l`antigène.'),
(1, 28, 'Facile', 'La puberté : ?', '0100', 'A lieu entre 9 et 11 ans.', 'A lieu entre 11 et 15 ans.', 'A lieu entre 15 et 18 ans.', 'A lieu à partir de 18 ans.'),
(1, 28, 'Facile', 'À la puberté : ?', '0101', 'Les testicules produisent une hormone appelée tostérone.', 'Les testicules produisent une hormone appelée testostérone.', 'Les ovaires produisent un seul type d`hormones.', 'La pluplart des filles ont leurs règles.'),
(1, 28, 'Facile', 'Lors de la puberté, les changements du corps : ?', '0111', 'Ne sont pas dus aux hormones.', 'Sont dus aux hormones produites par le cerveau.', 'Sont dus aux hormones produites par les organes génitaux.', 'Les hormones agissent sur des organes cibles.'),
(1, 28, 'Facile', 'Est-ce faux ? ?', '1010', 'Les testicules ne produisent pas les spermatozoïdes.', 'Les testicules produisent des gamètes.', 'Les ovaires ne produisent pas de gamètes.', 'Les ovaires produisent les ovules.'),
(1, 28, 'Facile', 'Lors du cycle de l`ovaire et de l`utérus : ?', '1001', 'L`ovulation dure 28 jours.', 'Les règles ont lieu au 14e jour du cycle.', 'La production d`hormones reste constante.', 'Le follicule se transforme progressivement en corps jaune.'),
(1, 28, 'Facile', 'La période de fécondité de la femme : ?', '0010', 'Dure 14 jours.', 'A lieu surtout avant l`ovulation.', 'Est déterminée par la durée de vie de l’ovule (24 heures) et par celle des spermatozoïdes (4 à 6 jours).', 'Est déterminée par la durée de vie de l`ovule qui est de 14 jours.'),
(1, 28, 'Facile', 'L`interruption volontaire de grossesse : ?', '1010', 'Se nomme IVG.', 'Est autorisée en France jusqu`à 8 semaines de grossesse.', 'Est autorisée en France jusqu`à 12 semaines de grossesse.', 'Est autorisée en France jusqu`à 16 semaines de grossesse.'),
(1, 28, 'Facile', 'Les végétaux verts sont : ?', '0101', 'Automorphes', 'Chlorophylliens', 'Les derniers maillons de la chaîne alimentaire', 'Autotrophes'),
(1, 28, 'Facile', 'La photosynthèse : ?', '1010', 'Se fait chez tous les végétaux verts.', 'Ne nécessite pas de lumière.', 'Produit de la matière organique.', 'Est un mécanisme que l`on retrouve aussi chez les animaux.'),
(1, 28, 'Facile', 'Les stomates : ?', '001', 'Sont des ouvertures visibles à l`œil nu.', 'Se trouvent surtout sur la face supérieure des feuilles.', 'Se ferment à l`obscurité.', ''),
(1, 28, 'Facile', 'La réaction chimique de la photosynthèse : ?', '0010', 'Ne nécessite pas de la lumière.', 'S`accompagne toujours de la respiration.', 'Produit du dioxygène.', 'Produit du CO2.'),
(1, 28, 'Facile', 'Une cellule animale : ?', '011', 'A besoin de CO2.', 'A besoin d`O2.', 'A besoin de nutriments.', ''),
(1, 28, 'Facile', 'La matière organique produite par la photosynthèse : ?', '0101', 'Ne circule que dans les feuilles.', 'Circule dans toute la plante.', 'Constitue la sève brute.', 'Se retrouve dans le phloème.'),
(1, 28, 'Facile', 'Le sang : ?', '110', 'Est transporté par des veines.', 'Est transporté par des artères.', 'Est transporté par la lymphe.', ''),
(1, 28, 'Facile', 'Un globule rouge : ?', '101', 'Est une hématie.', 'Transporte uniquement du dioxygène.', 'Transporte du dioxygène et du dioxyde de carbone.', ''),
(1, 28, 'Facile', 'La lymphe : ?', '001', 'N`est pas transparente.', 'Est rouge comme le sang.', 'Transporte des déchets.', ''),
(1, 28, 'Facile', 'Est-ce vrai : ?', '01', 'Les artères transportent le sang du cœur aux organes.', 'Les artères transportent le sang des organes jusqu`au cœur.', '', ''),
(1, 28, 'Facile', 'Les angiospermes : ?', '0011', 'Sont des plantes sans fleur.', 'Sont toujours hermaphrodites.', 'Sont des plantes à fleurs.', 'Ont des fleurs qui possèdent parfois des ovules.'),
(1, 28, 'Facile', 'Les oganes reproducteurs mâles d`une fleur se nomment : ?', '010', 'Les grains de pollen', 'Les étamines', 'Les ovules', ''),
(1, 28, 'Facile', 'Les organes reproducteurs femelles d`une fleur se nomment : ?', '0010', 'Les grains de pollen', 'Les étamines', 'Le pistil', 'Les ovules'),
(1, 28, 'Facile', 'La fécondation : ?', '1100', 'Est double chez les plantes à fleurs.', 'Nécessite un tube pollinique.', 'Transforme le pistil en graine et l`ovule en fruit.', 'Se fait avant la pollinisation.'),
(1, 28, 'Facile', 'Les caractères héréditaires d`un individu : ?', '0011', 'Proviennent uniquement des caractères génétiques du père.', 'Proviennent uniquement des caractères génétiques de la mère.', 'Sont transmis de génération en génération.', 'Constituent un programme génétique.'),
(1, 28, 'Facile', 'Les chromosomes : ?', '110', 'Portent le programme génétique de l`individu.', 'Sont aussi nombreux chez l`homme que chez la femme.', 'Constituent le phénotype.', ''),
(1, 28, 'Facile', 'Il y a : ?', '1001', '46 chromosomes chez une femme', 'Une paire de chromosomes supplémentaire chez l`homme : la paire XY', '24 paires de chromosomes chez l`Homme', 'Des gènes sur les chromosomes'),
(1, 28, 'Facile', 'Un gène : ?', '101', 'Peut avoir différentes versions appelées allèles.', 'Ne peut pas avoir différents allèles.', 'Se trouve à un endroit précis du chromosome.', ''),
(1, 28, 'Facile', 'Je suis de groupe sanguin A : ?', '1100', 'Si les deux chromosomes d`une même paire portent deux allèles A', 'Si l`un des chromosomes d`une même paire porte un allèle A et l`autre un allèle O.', 'Si l`un des chromosomes d`une même paire porte un allèle O et l`autre un allèle B.', 'Si l`un des chromosomes d`une même paire porte un allèle A et l`autre un allèle B.'),
(1, 28, 'Facile', 'L`ADN : ?', '1010', 'Est une longue molécule.', 'Signifie : acide dans le noyau.', 'Se trouve dans le chromosome.', 'Est une molécule visible à l`œil nu.'),
(1, 28, 'Facile', 'Un gamète : ?', '1010', 'Est une cellule reproductrice.', 'A 46 chromosomes.', 'A 23 chromosomes.', 'Peut posséder en même temps les chromosomes X et Y.'),
(1,31,'Facile',' Les chaînes de montagnes se forment à partir ','0100','du mouvement tectonique des plaques et la modification des roches','du mouvement tectonique des plaques et la subduction','de la modification des roches et la subduction','du bouleversement de l`asthénosphère'),
(1,31,'Facile','La lithosphère océanique est constituée de','0001','basaltes et gabbros','péridotites refroidies',' gabbros et péridotites','basaltes, gabbros et péridotites')
(1,31,'Facile','Dans une chaîne de montagne issue d’une collision existe un assemblage de roches appelé','1000',' ophiolites',' gabbros','serpentinites','basaltes'),
(1,31,'Facile','Quel caractère n`est pas spécifique d’une marge continentale passive ?','0001','Croûte continentale fracturée','Formation à la naissance d`un océan','Côté sous l`eau d`un continent',' Activité volcanique et sismique très intense'),
(1,31,'Facile','Quels sont les paramètres qui doivent modifier pour induire la disparition de la lithosphère océanique dans l`asthénosphère ?','0010','La quantité des roches  et leur viabilité',' La vivacité et la température','La température et la densité','La densité et la vivacité'),
(1,31,'Facile',' Quel minéral peut se former en dehors des zones de subduction ?','0010',' La jadéite','  Le grenat','La chlorite','La glaucophane'),
(1,31,'Facile','Quelle est la conséquence finale de la subduction?','0001',' L’ouverture d`un océan','Le rapprochement de 3 zones continentales','Un changement climatique','La collision de 2 zones continentales'),
(1,31,'Facile','Le Moho est défini comme la limite ','0100','entre l`asthénosphère et les plaques','entre la croûte terrestre et le manteau supérieur','entre la lithosphère continentale et la lithosphère océanique ','occidentale des plaques tectoniques'),
(1,31,'Facile',' Sous l`effet de l’augmentation de la température subie par la lithosphère océanique en s’enfonçant dans l’asthénosphère, les roches les plus profondes:','1000',' se déforment','durcissent  ','se cassent','se fissurent'),
(1,31,'Facile' 'Les nappes de charriage induisent ','0100','un soulèvement de roches','une migration de groupes rocheux','une modification de la nature des roches','   aucune transformation'),
(1,31,'Facile','L’érosion d’une chaîne de montagne est accompagnée par ','0001','son soulèvement','son enfoncement','une augmentation de l’épaisseur de la racine crustale','une diminution de l’épaisseur de la racine crustale'),
(1,31,'Facile',' La disparition des reliefs est causée par','0001',' la collision',' la subduction',' l’obduction','l’effondrement des reliefs'),
(1,31,'Facile','La datation des roches continentales est effectuée par :', '0010','datation relative','anomalie magnétique',' radiochronologie','thermoluminescence'),
(1,31,'Facile','Les sédiments transportés par l’eau se déposent en fonction','0010','de leur taille','du débit du courant','de leur taille et du débit du courant','de leur forme et du dédit du courant'),
(1,32,'Facile','L’érosion et le transport des sédiments sont principalement assurés par','1000','les végétaux',' le vent','le gel et le dégel','  l’eau'),
(1,31,'Facile','L’âge de la croûte continentale est de ','1000','4000 Ma','400 Ma',' 40 Ma',' 4 Ma'),
(1,31,'Facile','Les particules d’érosion transportées se déposent dans','1000','un bassin sédimentaire','une montagne ancienne','une zone de collision','une montagne récente'),
(1,31,'Facile','La diagénèse correspond à la formation des roches','0001','magmatiques',' métamorphiques','volcaniques',' sédimentaires'),
(1,31,'Facile','En radiochronologie, quelle est la proposition vraie ','1000',' L’isotope père radioactif se transforme à en isotope fils     correspondant stable','L’isotope père stable se transforme en isotope fils correspondant     radioactif','   L’isotope père radioactif se transforme en isotope fils     correspondant radioactif','  L’isotope père stable se transforme en isotope fils correspondant     stable'),
(1,31,'Facile',' Concernant la droite isochrone, sa pente ','','diminue avec le temps','diminue avec l’érosion','augmente avec le temps','augmente avec l’érosion'),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', 'Quel langage n`est pas compilé ?', '001', 'C++', 'Java', 'HTML', ''),
(1, 37, 'Facile', 'Quel type n`est pas primitif en C++ ?', '0100', 'char', 'string', 'int', 'float'),
(1, 37, 'Facile', 'Quelle est la spécificité du Malbolge ?', '01', 'C`est le langage le plus simple', 'C`est un langage incompréhensible', '', ''),
(1, 37, 'Facile', 'Lequel de ces langages est le plus vieux ?', '0010', 'C', 'Java', 'Fortran', 'Pascal'),
(1, 37, 'Facile', 'En quelle année a été créé le Fortran ?', '0100', '1970', '1957', '1949', '1964'),
(1, 37, 'Facile', 'Qui est le créateur du C++ ?', '010', 'Brian Kernighan', 'Bjarne Stroustrup', 'Dennis Ritchie', ''),
(1, 37, 'Facile', 'Quel langage est utilisé pour iOS ?', '011', 'Java', 'Objective-C', 'Swift', ''),
(1, 37, 'Facile', 'Quel est l`équivalent Java du std::vector en C++ ?', '0100', 'Set', 'ArrayList', 'LinkedList', 'Map'),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 40, 'Facile', 'Où ont été trouvés les plus vieux ossements humains ?', '1000', 'En Afrique', 'En Asie', 'En Europe', 'En Amérique'),
(1, 40, 'Facile', 'L`homme moderne est un', '10', 'Homo sapiens', 'Home neandertalis', '', ''),
(1, 41, 'Facile', 'L`écriture de l`Egypte antique se nomme', '10', 'Hiéroglyphe', 'Cursive', '', ''),
(1, 41, 'Facile', 'CléopÃ¢tre régna sur l`Egypte vers', '1000', '40 avant Jésus-Christ', '400 avant Jésus-Christ', '40 après Jésus-Christ', '400 après Jésus-Christ'),
(1, 41, 'Facile', 'Vrai ou Faux : Vercingétorix était un soldat romain', '01', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Vrai ou Faux : Vercingétorix a déposé les armes à Alexia', '10', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Jules César est un personnage datant de', '1000', 'L`Antiquité', 'Le Moyen-Ã¢ge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Clovis est né vers', '010', '1180', '466', '1980', ''),
(1, 42, 'Facile', 'Jeanne d`Arc est un personnage datant de', '0100', 'L`Antiquité', 'Le Moyen-Ã¢ge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Vrai ou Faux : Dagobert 1er régna avant Clovis', '01', 'Vrai', 'Faux', '', ''),
(1, 42, 'Facile', 'Quelle dynastie succéda à celle des Mérovingiens ?', '1000', 'Les Carolingiens', 'Les Capétiens', 'Les Valois', 'Les Bourbons'),
(1, 42, 'Facile', 'Charlemagne était le fils de ', '010', 'Clovis', 'Pépin le Bref', 'Hugues Capet', ''),
(1, 42, 'Facile', 'Sous quels autres noms connaÃ®t-on Louis IX', '110', 'Saint-Louis', 'Le Prudhomme', 'Louis le Bon', ''),
(1, 43, 'Facile', 'Quel élément n`est pas du Moyen-Ãge ?', '001', 'Les chÃ¢teaux forts', 'Les chevaliers', 'Les montgolfières', ''),
(1, 43, 'Facile', 'A qui doit-on l`invention de l`imprimerie ?', '0100', 'Léonard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'A qui doit-on l`invention de la machine à vapeur ?', '0010', 'Léonard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'Léonard de Vinci a travaillé pour ', '0100', 'Jules César', 'François 1er', 'Louis XIV', 'Napoléon'),
(1, 43, 'Facile', 'Parmi ces personnages qui étaient explorateurs ?', '1110', 'Marco Polo', 'Magellan', 'Christophe Collomb', 'Guttenberg'),
(1, 44, 'Facile', 'Louis XIV était surnommé', '10', 'Le roi Soleil', 'Le roi fainéant', '', ''),
(1, 44, 'Facile', 'Molière était ', '001', 'Chevalier', 'Roi', 'Ecrivain', ''),
(1, 44, 'Facile', 'La Révolution Française a eu lieu en ', '0100', '1515', '1789', '1804', '1968'),
(1, 44, 'Facile', 'La Bastille était ', '100', 'Une prison', 'La résidence du Roi', 'Une auberge', ''),
(1, 44, 'Facile', 'Quel roi fut guillotiné ?', '010', 'Henri IV', 'Louis XVI', 'Louis-Philippe', ''),
(1, 44, 'Facile', 'Napoléon Bonaparte devint empereur des Français en ', '001', '800', '1792', '1804', ''),
(1, 44, 'Facile', 'Le Général de Gaulle a combattu', '0001', 'Les Romains avec Vercingétorix', 'Les Anglais avec Jeanne d`Arc', 'Les Russes avec Napoléon', 'Les Allemands avec Churchill'),
(1, 45,'Facile','A quelle période sont apparus nos ancêtres ?','001','1 ou 2 millions de notre ère','1 ou 2 millions avant notre ère.','3 ou 4 millions avant notre ère',''),
(1, 45,'Facile','Où sont apparus nos ancêtres ?','010','En Amérique','En Afrique','En Australie',''),
(1, 45,'Facile','Comment s`appelle la révolution qui apporte la sédentarisation ?','010','La révolution française','La révolution Néolithique','La révolution cathodique',''),
(1, 45,'Facile',' Citez un Australopithèque parmi ?','010','Marie','Lucy','Sophie',''),
(1, 45,'Facile',' Quel est l`ancêtre direct de l`Homme ?','001','Cro-Mission','Cro-Mignon','Cro-Magnon',''),
(1, 45,'Facile','Qui sculpte des statuettes ?','100','Cro-Magnon','Lucy','Néanderthal',''),
(1, 45,'Facile','Où se diffuse la révolution Néolithique ?','100','Le Proche-Orient','L`Europe de l`Est','La Chine',''),
(1, 45,'Facile','Quel est l`élément fondamental de l`agriculture ?','001','La chasse','La pêche','La domestication',''),
(1, 45,'Facile','Quel est le premier animal domestiqué ?','001','Le mouton','Le cheval','Le chien',''),
(1, 45,'Facile','Quel est l`ancêtre du chien ?','100','Le loup','Le lynx','Le renard',''),
(1, 45,'Facile',' Par quoi est coupé l`épis de blé ?','100','La faucille','Le peigne','Le sécateur',''),
(1, 45,'Facile','Quand apparaît l`outil de la précédente question ?','001','-2000','-3000','-4000',''),
(1, 45,'Facile','Comment s`appellent les premiers signes d`écriture ?','100','Les pictogrammes','Les signes géométriques','Les gravures',''),
(1, 45,'Facile','Où sont apparus les premiers signes d`écriture ?','001','En Amérique','En Afrique du Sud','Au Croissant Fertile',''),
(1, 45,'Facile','Quand sont apparus les signes cunéiformes ?','010','-2700','-2400','-2800',''),
(1, 45,'Facile','Qui inventent les hiéroglyphes ?','001','Les Phéniciens','Les Grecs','Les Egyptiens',''),
(1, 45,'Facile',' Est ce que la IIIème république se fonde sur une défaite?','001','non','je ne sais pas','oui',''),
(1, 45,'Facile','Que se passe t il en 1871?','100','La Commune','La Municipale','La Guerre',''),
(1, 45,'Facile','Que se passe t il le 28 janvier 1871?','100','La France capitule','La France gagne la guerre','La France ne fait rien',''),
(1, 45,'Facile','Qui dirige le gouvernement provisoire?','001','Adolphe tlier','Adolphe sthiers','Adolpe Thiers',''),
(1, 45,'Facile','Qu`adopte la Commune?','100','le drapeau rouge','le drapeau noir','le drapeau vert',''),
(1, 46,'Facile','La démocratie est le pouvoir…?','0010','d’un seul','d’un groupe de personnes','de l’ensemble des citoyens','de l’argent de l’ensemble des citoyens (en grec «démos» est le peuple)'),
(1, 46,'Moyen','On connaît Athènes pour…?','1000','sa démocratie','son oligarchie','sa tyrannie','sa ploutocratie'),
(1, 46,'Moyen','L’ostracisme est…','0100','un exil volontaire','un exil forcé','une forme de gouvernement','une forme de pouvoir'),
(1, 46,'Moyen','L’assemblée du peuple à Athènes s’appelle :?','0100','la boulè','l’ecclésia','l’Agora','l’Acropole'),
(1, 46,'Moyen',' L’assemblée du peuple se réunit…','1000','sur l’Agora','au Pirée','à Délos','dans le bouleutèrion'),
(1, 46,'Moyen',' Les magistrats sont au pouvoir pour…','0100','un mois','un an','cinq ans','dix ans'),
(1, 46,'Moyen','Les magistrats ont des pouvoirs…','0010','dans tous les domaines','dans plusieurs domaines','dans un domaine particulier','ils n’ont pas de pouvoir politique'),
(1, 46,'Moyen','Les stratèges sont…?','1000','des magistrats en charge de la guerre','des magistrats en charge de la justice','des magistrats en charge de l’économie','des magistrats en charge de l’instruction'),
(1, 46,'Moyen','Les grands stratèges d’Athènes sont…','0001','Hérodote et Thucydide','Darius et Xerxès','Solon et Clisthène','Thémistocle et Périclès'),
(1, 46,'Moyen','À Athènes, la citoyenneté est…','0001','facile à obtenir','fondée sur la richesse','réservée à l’aristocratie',' très fermée et héréditaire'),
(1, 46,'Moyen','Les habitants d’Athènes sont-ils tous citoyens ?','01','oui','non','',''),
(1, 46,'Moyen','Hérodote et Thucydide sont…?','1000','des historiens grecs','de grands stratèges d’Athènes','des rois perses ennemis d’Athènes','des hommes politiques de Sparte'),
(1, 46,'Moyen','Les Guerres Médiques opposent…?','0100','Sparte et les Romains','Athènes et les Perses','Athènes et Sparte','La Grèce et Carthage'),
(1, 46,'Moyen','La Ligue de Délos est…?','1000','une alliance militaire entre les cités grecques','une alliance militaire entre la Grèce et Rome','un mouvement politique de démocrates','une révolution d`oligarques'),
(1, 46,'Moyen',' Lors de la guerre du Péloponnèse, qui est vainqueur ?','0001','Thèbes','Athènes','Délos','Sparte'),
(1, 46,'Moyen',' À la fin du V-ème siècle, Athènes connaît…?','0100','une dictature','une tyrannie','une oligarchie','une démocratie'),
(1, 46,'Moyen',' Qui fut un grand écrivain pour le théâtre ?','1000','Eschyle','Platon','Socrate','Alcibiade'),
(1, 46,'Moyen','Les métèques sont, à Athènes,…?','0010','des esclaves','des barbares','des étrangers','des ennemis'),
(1, 46,'Moyen','Le Pirée et l’Acropole sont respectivement…?','1000','un port et une colline sacrée','des villes de la banlieue d’Athènes','des temples dédiés à Athéna','des montagnes de l’Attique'),
(1, 46,'Moyen','La Sécurité Sociale…?','100','est créée par les ordonnances de 1945','protège dès son origine l’ensemble des Français','connaît un équilibre financier',''),
(1, 46,'Moyen',' Le baby-boom se prolonge pendant toute la durée des «Trente Glorieuses» :','01','Vrai','Faux','',''),
(1, 46,'Moyen','La loi Pisani…','10','concerne l’industrie','concerne l’agriculture','est signée en 1956',''),
(1, 46,'Moyen',' Le SMIG…','001','est créé en 1947','est dès son origine relevé automatiquement selon la montée de l’indice du coût de la vie','sera généralisé sous la présidence de Valéry Giscard D’Estaing',''),
(1, 46,'Moyen',' Le droit de vote a été accordé aux femmes en…','0100','1918','1944','1958','1968'),
(1, 46,'Moyen','La plan Monnet donne la priorité…','100','au développement de l’industrie lourde','à la création de la CECA','aux équipements collectifs',''),
(1, 46,'Moyen','Identifiez la proposition fausse au sein de ces affirmations sur l’évolution économique sous la IVème République :','0001','De 1949 à 1957, la production industrielle s’accroît de 70%','De 1949 à 1957, l’industrie de la chimie s’accroît de 130%','De 1949 à 1957, la pouvoir d’achat du salaire horaire brut s’accroît de 40%','De 1949 à 1957, l’investissement pour le logement s’accroît de 50%'),
(1, 46,'Moyen',' Le mouvement poujadiste…?','0010','est un mouvement qui se développe dans les années 60','est un mouvement paysan','est un mouvement de classes moyennes','est un mouvement ouvrier'),
(1, 46,'Moyen','Entre 1953 et 1973, le pourcentage de ménages possédant une télévision passe de 5 à 80% :','10','Vrai','Faux','',''),
(1, 46,'Moyen','Le Traité de Rome…?','010','abolit tous les droits de douane entre les pays membres','abolit à terme les droits de douane entre les pays membres','instaure une monnaie de compte commune entre les pays membres',''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 48, 'Facile', 'Combien y a-t-il de continents ?', '001', '2', '4', '6', ''),
(1, 48, 'Facile', 'Quel fleuve n`est pas un fleuve Français ?', '0010', 'La Garonne', 'La Loire', 'Le Nil', 'La Seine'),
(1, 48, 'Facile', 'Quel est le plus long fleuve de France ?', '0001', 'La Garonne', 'Le Rhône', 'La Seine', 'La Loire'),
(1, 48, 'Facile', 'Quels massifs montagneux sont en France ?', '1110', 'Les Alpes', 'Les Pyrennées', 'Le Massif Central', 'L`Himalaya'),
(1, 48, 'Facile', 'Combien y a t-il de saisons en Europe ?', '10', '4', '2', '', ''),
(1, 48, 'Facile', 'En hiver, les nuits sont', '100', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Au printemps, les nuits sont', '010', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Combien y a-t-il de jours dans une année ?', '100', '365-366 jours', '255-256 jours', '405-406 jours', ''),
(1, 48, 'Facile', 'Combien de jours comprend le mois de Mars ?', '001', '29', '30', '31', ''),
(1, 48, 'Facile', 'Une année de 366 jours s`appelle une année ...', '010', 'bipolaire', 'bissextile', 'bipode', ''),
(1, 48, 'Facile', 'Une année bissextile arrive tous les ', '1000', '4 ans', '5 ans', '6 ans', '7 ans'),
(1, 48, 'Facile', 'Vrai ou Faux : Le Soleil tourne autour de la Terre', '01', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Terre tourne sur elle-même', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Lune tourne autour de la Terre', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'La Lune tourne autour de la Terre en environ', '1000', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre tourne autour du Soleil en ', '0001', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre fait un tour sur elle-même en ', '100', '1 jour', '1 mois', '1 an', ''),
(1, 48, 'Facile', 'Une journée dure ', '10', '24 heures', '12 heures', '', ''),
(1, 48, 'Facile', 'Le Soleil se lève', '1000', 'à l`Est', 'à l`Ouest', 'au Nord', 'au Sud'),
(1, 48, 'Facile', 'Comment appelle-t-on Nord, Est, Ouest, Sud', '001', 'Les points noirs', 'Les points blancs', 'Les points cardinaux', ''),
(1, 48, 'Facile', 'Quelles mers bordent la France ?', '101', 'Mer méditerrannée', 'Mer rouge', 'La Manche', ''),
(1, 48, 'Facile', 'A combien culmine le Mont Blanc ?', '100', '4807', '8848', '5891', ''),
(1, 48, 'Facile', 'Quels pays ont frontière commune avec la France ?', '110', 'La Belgique', 'L`Allemagne', 'La Russie', ''),
(1, 48, 'Facile', 'Quelle la capitale de la France ?', '100', 'Paris', 'Lille', 'Marseille', ''),
(1, 48, 'Facile', 'Combien de pays comprend l`union européenne ?', '010', '17', '27', '37', ''),
(1, 49, 'Difficile', 'Autrefois la Birmanie, aujourdhui ', '100', 'Myanmar', 'Magyar', 'Malawi', ''),
(1, 49, 'Difficile', 'La Rhodésie du Sud fut ainsi nommée de 1895 jusqu`en 1980 où elle devient', '010', 'Le Zimbabwe', 'Le Zambèze', 'La Zambie', ''),
(1, 49, 'Difficile', 'Le royaume de siam à été fondé en 1350 et devient en 1939 le royaume de', '10', 'Thaïlande', 'Pagan', '', ''),
(1, 49, 'Moyen', 'La tchécoslovaquie est un Etat souvrain qui exista de 1918 à 1992 avant de devenir suite à sa dissolution', '001', 'La Tchéquie', 'La Slovaquie', 'La Slovaquie et la Tchéquie', ''),
(1, 49, 'Moyen', 'D`abord colonie de l`AOF en 1919, la Haute-Volta fut une république en 1958 afin de devenir en 1984', '0001', 'La Guinée', 'Le Rwanda', 'La Mozambique', 'Le Burkina Faso'),
(1, 49, 'Difficile', 'En 1894, l`empire colonial français intègre le royaume du Dahomey à l`AOF qui deviendra en 1960, la république du Dahomey avant de devenir en 1990 république du ', '010', 'Lesotho', 'Bénin', 'Burundi', ''),
(1, 49, 'Difficile', 'Le Swaziland, petite monarchie enclavée au sud de l`Afrique, prit en 2018 le nom de', '10', 'Eswatini', 'Nambie', '', ''),
(1, 49, 'Facile', 'La république du Zaïre était le nom de l`actuelle', '0100', 'République de Guinée Equatoriale', 'République Démocratique du Congo', 'République Centrafricaine', 'République du Congo'),
(1, 49, 'Facile', 'Les océans recouvrent combien de % sur la Terre ?', '1000', '70.8', '65.8', '20.8', '90.8'),
(1, 49, 'Facile', 'En mètres, quelle est la profondeur de l`océan Pacifique ?', '0010', '5 000 m', '3 000 m', '10 925 m', '15 000 m'),
(1, 49, 'Facile', 'Pour 1Kg d`eau de mer, combien a-t-on de grammes de sel ?', '0001', '10 à 20 g', '100 g', '60 à 70 g', '30 à 40 g'),
(1, 49, 'Facile', 'On dit que les marées sont influencées par la Lune. Est-ce vrai ou faux ?', '01', 'Faux', 'Vrai', '', ''),
(1, 49, 'Facile', 'En pourcentage, quelle est la superficie totale des océans à la surface de notre planète ?', '1000', '71%', '61%', '51%', '81%'),
(1, 49, 'Facile', 'Quelle est la particularité des océans de notre planète ?', '010', 'Les océans ne sont pas composés avec de l`eau', 'Tous les océans sont reliés entre eux', 'On ne pas passé d`un océan à un autre car ils sont bloqués par les continent', ''),
(1, 49, 'Facile', 'Combien y-a-t-il d`océans sur la Terre ?', '0001', '4', '3', '6', '5'),
(1, 49, 'Moyen', 'A l`échelle mondiale, le commerce de marchandises se fait essentiellement par quelle voie', '0100', 'Aérienne', 'Maritime', 'Ferroviaire', 'Routière'),
(1, 49, 'Moyen', 'Quelle est la part des échanges commerciaux s`effectuant par voie maritime ?', '0010', '50%', '70%', '80%', '100%'),
(1, 49, 'Facile', 'Quel est le plus grand port du monde ?', '0100', 'Bordeaux', 'Shanghaï', 'Rotterdam', 'Singapour'),
(1, 49, 'Moyen', 'Sur les 10 premiers ports du monde, combien sont chinois ?', '100', '7', '3', '5', ''),
(1, 49, 'Facile', 'Quel est le 1er port d`Europe ?', '0001', 'Marseille/fos-sur-Mer', 'Le Havre', 'Barcelone', 'Rotterdam'),
(1, 49, 'Facile', 'Qu`est-ce qu`un canal ?', '001', 'Un passage étroit mais natural entre deux océans', 'Un passage étroit mais natural entre deux mers', 'Une rivière artificielle creusée par l`Homme', ''),
(1, 49, 'Moyen', 'Quels océans sont reliés par le canal de Panama ?', '0100', 'Atlantique et Indien', 'Atlantique et Pacifique', 'Pacifique et Indien', 'Atlantique et Glacial Arctique'),
(1, 49, 'Facile', 'Qu`est-ce qu`un détroit ?', '0001', 'Un rivière artificielle creusée par l`homme', 'Bande de mer étroite entre deux étendues de mers ou d`océans', 'Un dé à trois faces', 'Bande de mer étroite entre deux étendues de terre'),
(1, 49, 'Moyen', 'Les espaces marins ont un rôle de régulateur climatique vitale pour l`humanité ?', '1000', 'Vrai', 'Faux', 'Seulement la nuit', 'Seulement la journée'),
(1, 49, 'Moyen', 'Dans quel département se trouve le Grésivaudan ?', '010', 'La Lozère', 'l`Isère', 'La Haute-Loire', ''),
(1, 50, 'Moyen', 'Dans quel département se trouve le château de Malesherbes ?', '10', 'Le Loiret', 'L`Aisne', '', ''),
(1, 50, 'Moyen', 'Dans quel département se trouve la forêt d`Hourtin ?', '001', 'L`Yonne', 'Le Bas-Rhin', 'La Gironde', ''),
(1, 50, 'Moyen', 'Dans quel département se trouve la ville fortifiée de Saint-Bonnet-le-Château ?', '010', 'Les Pyrénées-Atlantiques', 'La Loire', 'Les Hautes-Pyrénées', ''),
(1, 50, 'Moyen', 'Dans quel département se trouve la basilique Notre-Dame-de-Buglose ?', '001', 'La Creuse', 'Le Cher', 'Les Landes', ''),
(1, 50, 'Moyen', 'Parmi ces états lequel est traversé par l`Equateur ?', '1000', 'L`Indonésie', 'L`Argentine', 'L`Afrique du Sud', 'L`Afganistan'),
(1, 50, 'Facile', 'La Guinée est un pays...?', '0100', 'D`Europe', 'D`Afrique', 'D`Amérique', 'D`Océanie'),
(1, 50, 'Moyen', 'Parmi ces villes laquelle se trouve la plus au nord ?', '0010', 'Nairobi', 'Pretoria', 'Tombouctou', 'Bujumbura'),
(1, 50, 'Difficile', 'Parmi ces pays lequel est le plus vaste ?', '0001', 'La Lituanie', 'La Letonie', 'La Géorgie', 'La Norvège'),
(1, 50, 'Difficile', 'Odessa est une grande ville d...?', '010', 'Du Canada', 'D`Ukraine', 'De Russie', ''),
(1, 50, 'Moyen', 'Lagos est une grande ville ...?', '001', 'Du Kenya', 'D`Afrique du Sud', 'Du Nigéria', ''),
(1, 50, 'Moyen', 'Parmi ces états lequel est un pays de l`hémisphère sud ?', '1000', 'L`Angola', 'La Chine', 'Le Sénégal', 'Le Soudan'),
(1, 50, 'Facile', 'Lequel de ces pays a déjà mis seul un satellite en orbite ?', '100', 'La Corée du Sud', 'La Turquie', 'Le Pérou', ''),
(1, 50, 'Difficile', 'Parmi ces pays lequel touche les Carpates ?', '01', 'La Grèce', 'La Slovaquie', '', ''),
(1, 50, 'Moyen', 'Pamis ces pays lequel est le plus vaste ?', '001', 'L`Equateur ', 'L`Urugay', 'L`Argentine', ''),
(1, 50, 'Moyen', 'Quelle mer ou Océan est bordé par le Liberia ?', '0001', 'Océan Indien', 'La mer Rouge', 'La mer Noire', 'L`Océan Atlantique'),
(1, 50, 'Difficile', 'Parmie ces nations laquelle est la plus peuplée ?', '0100', 'Le Cambodge', 'Le Viet-Nam', 'Le Laos', 'La Thaïlande'),
(1, 50, 'Moyen', 'Quel est le nombre d`habitants de la France ? (en millions)', '1000', '66', '21', '32', '134'),
(1, 50, 'Difficile', 'Oman est...', '0010', 'Un Royaume', 'Une république Populaire', 'Un Sultanat', 'Un émirat'),
(1, 50, 'Facile', 'Parmi ces pays lequel n`est pas limitrophes à la Pologne?', '010', 'Bielorussie', 'Hongrie', 'Lituanie', ''),
(1, 50, 'Moyen', 'Parmi ces villes laquelle se trouve le plus au nord ?', '0001', 'Lagos', 'Addis-Abebas', 'Brazzaville', 'Alger'),
(1, 50, 'Difficile', 'Parmi ces états lequel est un pays d`Afrique australe ?', '001', 'La Birmanie', 'Le Tchad', 'Le Zimbabwe', ''),
(1, 50, 'Difficile', 'Dans quel pays coule l`Ebre ?', '01', 'Le Portugal', 'L`Espagne', '', ''),
(1, 50, 'Difficile', 'Parmi ces pays lequel n`a pas d`accès à la mer ?', '1000', 'Le Bostwana', 'La Nambie', 'Le Kenya', 'L`Angola'),
(1, 50, 'Moyen', 'Parmi ces villes laquelle se trouve la plus au sud ?', '001', 'Madrid', 'Istambul', 'Tokyo', ''),
(1, 50, 'Moyen', 'Parmi ces états lequel est traversé par l`Equateur ?', '010', 'La Syrie', 'La Colombie', 'La Tunisie', ''),
(1, 51, 'Difficile', 'Parmi ces pays lequel est le plus vaste ?', '1000', 'Niger', 'Nigéria', 'Cameroun', 'Burkina Faso'),
(1, 51, 'Difficile', 'Auckland est une grande ville de quel pays ?', '010', 'Indonésie', 'Nouvelle Zélande', 'Paragey', ''),
(1, 51, 'Moyen', 'Lequel de ces pays est dans l`Union Européenne ?', '0100', 'Norvège', 'Hongrie', 'Islande', 'Moldavie'),
(1, 51, 'Difficile', 'Parmi ces pays lequel touche l`Himalaya ?', '0001', 'L`Iran', 'La Mongolie', 'Le Laos', 'Le Bhoutan'),
(1, 51, 'Difficile', 'Quelle mer ou Océan est bordé par la Norvège ?', '1000', 'Mer de Barents', 'Mer de Laptev', 'Mer Baltique', 'Océan Pacifique'),
(1, 51, 'Facile', 'Parmi ces pays lequel n`est pas limitrophes à la Russie ?', '0010', 'Pologne', 'Corée du Nord', 'Moldavie', 'Norvège'),
(1, 51, 'Difficile', 'Altitude de l`Everest ?', '0001', '8648 m', '8748 m', '8948 m', '8848 m'),
(1, 51, 'Difficile', 'Quel est le 2ème plus haut sommet du monde ?', '0100', 'Lhose', 'K2', 'Kangchenjunga', 'Makalu'),
(1, 51, 'Difficile', 'Dans quelle chaine de montagnes se situe l`Aconcagua ?', '100', 'Cordilière des Andes', 'Caucase', 'Montagne rocheuses', ''),
(1, 51, 'Moyen', 'Quel est le point culminant du continent africain ?', '0001', 'Mont Kenya', 'Mont Speke', 'Mont Stanley', 'Kilimandjaro'),
(1, 51, 'Moyen', 'Quel est le deuxième sommet des Alpes après le Mont Blanc ?', '01', 'Mont Cervin', 'Mont Rose', '', ''),
(1, 51, 'Moyen', 'Point culminant de l`Espagne ?', '10', 'Teide', 'Pic Aneto', '', ''),
(1, 51, 'Difficile', 'Combien y a-t-il de sommets de + de 8 000 m sur la planète ?', '0001', '10', '16', '12', '14'),
(1, 51, 'Difficile', 'Où se situe le Mont Mac Kingley ?', '0100', 'Patagonie', 'Alaska', 'Groënland', 'Cordilières des Andes'),
(1, 51, 'Difficile', 'Où se situe le Mont Elbrouz ?', '001', 'Alpes', 'Domolites', 'Caucase', ''),
(1, 51, 'Difficile', 'Quel est le point culminant du massif de la Vanoise ?', '100', 'La Grande Casse', 'La Grande Motte', 'Le Mont Pourri', ''),
(1, 51, 'Facile', 'Quel fleuve passe par la ville du Caire ?', '010', 'L`Assioût', 'Le Nil', 'Le Nasser', ''),
(1, 51, 'Moyen', 'Quel fleuve passe par la ville de la Nouvelle-Orléans ?', '001', 'Red', 'Rio Grande', 'Mississipi', ''),
(1, 51, 'Difficile', 'Quel fleuve passe par la ville de Lisala ?', '100', 'Congo', 'Sankuru', 'Tshuapa', ''),
(1, 51, 'Facile', 'Quel fleuve passe par la ville de Bordeaux ?', '001', 'La Loire', 'Le Rhône', 'La Garonne', ''),
(1, 51, 'Moyen', 'Quelle capitale européenne abrite la Grand-Place, renommée pour sa richesse ornementale ?', '0100', 'Vienne', 'Bruxelles', 'Amsterdam', 'Paris'),
(1, 51, 'Moyen', 'Où situez-vous le site mégalithique de Stonehenge ?', '100', 'An Agleterre', 'En Ecosse', 'Au Pays de Galles', ''),
(1, 51, 'Difficile', 'Quelle est l`unité monétaire et la devise d`Haïti ?', '010', 'La Cruche', 'La Gourde', 'La Courge', ''),
(1, 51, 'Difficile', 'Où devez-vous vous rendre pour admirer le temple de Borobudur ?', '100', 'En Indonésie', 'En Malasie', 'En Thaïlande', ''),
(1, 51, 'Difficile', 'Quel pays d`Afrique de l`Ouest correspond au territoire de l`ancien Royaume de Dahomey ?', '001', 'Le Togo', 'Le Ghana', 'Le Bénin', ''),
(1, 52, 'Facile', 'Quels verbes sont du 1er groupe ?', '011', 'Boire', 'Manger', 'Péter', ''),
(1, 52, 'Facile', 'Quels verbes sont du 2ème groupe ?', '100', 'Finir', 'Fuir', 'Courrir', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ème groupe ?', '011', 'Subir', 'Aller', 'Boire', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ème groupe ?', '1010', 'Entrevoir', 'Lier', 'Lire', 'Boucher'),
(1, 52, 'Facile', 'Présent  : Vous (manger)', '01', 'manger', 'mangez', '', ''),
(1, 52, 'Facile', 'Futur : Vous (courir)', '01', 'courrier', 'courrez', '', ''),
(1, 53, 'Facile', 'Imparfait : Ils (finir)', '01', 'finirent', 'finissaient', '', ''),
(1, 53, 'Facile', 'Passé Composé : Tu (aller)', '01', 'as allé', 'es allé', '', ''),
(1, 53, 'Facile', 'Quel temps : On entend le rossignol chanter', '01', 'Passé composé', 'Présent', '', ''),
(1, 53, 'Facile', 'Quel temps : La fusée décollera à 12 heures', '01', 'Présent', 'Futur', '', ''),
(1, 53, 'Facile', 'Quel temps : Nous étions les rois du monde', '01', 'Présent', 'Imparfait', 'Futur', ''),
(1, 53, 'Facile', 'OÃ¹ est le verbe : Le chat mange une souris', '010', 'chat', 'mange', 'souris', ''),
(1, 53, 'Facile', 'Qui est le nom noyau : La petite fille aux alumettes', '001', 'alumettes', 'petite', 'fille', ''),
(1, 53, 'Facile', 'Combien de verbes : Le chat suit des yeux le mulot, se tapit, puis bondit dessus', '001', '1', '2', '3', ''),
(1, 53, 'Facile', 'COD ou COI (une souris) : Le chat mange une souris', '10', 'COD', 'COI', '', ''),
(1, 53, 'Facile', 'COD ou COI (à sa grand-mère) : La fille écrit à sa grand-mère', '01', 'COD', 'COI', '', ''),
(1, 53, 'Facile', 'Nature de "Sous le rebord de la fenêtre"', '010', 'CC de temps', 'CC de lieu', 'CC de manière', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Difficile', 'Branche du langage consacrée à la signification des mots : ', '0001', 'La phonétique ', ' La didactique', ' La dialectique', '  La sémantique'),
(1, 56, 'Difficile', 'Lequel de ces verbes est un verbe irrégulier ?', '0010', 'Abêtir ', ' Asservir ', ' Cueillir ', 'Haïr '),
(1, 56, 'Difficile', 'Quel verbe est mal orthographié ?', '1000', 'Transcande ', 'Exceller ', ' Proroger', 'Exaucer '),
(1, 56, 'Difficile', 'Quel est le pluriel de « nouveau-né » ?', '100', ' nouveaux-nés', 'nouveau-nés ', ' nouveaux-né', ' '),
(1, 56, 'Difficile', 'quel est le verbe mal conjugué ?', '0001', 'Que tu essaies ', 'Que tu appelles ', ' Que tu prennes', 'Que tu ais '),
(1, 56, 'Difficile', 'Quelle proposition n`est pas un couple d`antonymes ?', '1000', 'Téméraire-timoré ', 'Affairé-oisif ', ' Egoïste-intégre', 'Certain-aléatoire '),
(1, 56, 'Difficile', 'Un de ces mots est mal accentué, lequel ?', '10', ' Tétard', ' Imbécillité ', '', ''),
(1, 56, 'Difficile', 'Un de ces mots est correctement orthographié, lequel ?', '0100', ' Ocre', 'Occre', 'Aucre ', 'Hocre '),
(1, 56, 'Difficile', 'Lequel de ces mots est un palindrome ?', '10', 'Kayak ', ' Bonbon', '', ''),
(1, 56, 'Difficile', 'Quelle est la proposition correctement orthographiée ?', '0001', ' Douze mille lieues', 'Cinq milliard de gens ', 'Trois cents une maisons ', 'Quatre cent prisonniers'),
(1, 56, 'Difficile', 'Lequel de ces mots n`est pas du genre masculin ?', '0101', ' Hémisphère', 'Armistice ', '  Anagramme', 'Pamplemousse '),
(1, 56, 'Difficile', 'Lequel de ces verbes ne double pas son t ?', '01', '  At_endre', ' Prét_endre ', '', ''),
(1, 56, 'Difficile', 'Lequel de ces mots n`a pas d`accent circonflexe ? ' , '001', ' Le gout', 'Le gite ', 'Le bagout',''),
(1, 56, 'Difficile', '« Préparer d`avance » est : ', '0010', ' Une litote', 'Un barbarisme', 'Un pléonasme', 'Un oxymore'),
(1, 56, 'Difficile', 'Quel est l`intrus parmi ces propositions ?', '001', 'Une chatterie', 'Un canotier', 'Un haras', ''),
(1, 56, 'Difficile', 'Quelle est la bonne orthographe ?', '10', 'Huis clos ', 'Huit clô ', '', ''),
(1, 56, 'Difficile', 'Quelle est la forme correcte ?', '01', 'Je sursoirrai ', 'Je surseoirai ', '', ''),
(1, 56, 'Difficile', 'Quelle est la proposition correctement orthographiée ?', '100', ' Des pantalons marrons', ' Des pantalons maron', 'Des pantalons marron', ''),
(1, 56, 'Difficile', 'Quelle est la bonne orthographe ?', '01', 'Bouque-émissaire', 'Bouc émissaire', '', ''),
(1, 56, 'Difficile', 'Quel est le pluriel de gratte-ciel ?', '001', 'Grattes-cieux ', 'Gratte-ciels ', 'Grattes-ciels ', ''),
(1, 56, 'Difficile', 'Quelle est la formulation inexacte ?', '010', 'Tu révèles', 'Je céde ', 'J`assaillirai ', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to swear', '010', 'sweared', 'swore', 'swearing', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to freeze', '100', 'froze', 'frozed', 'frozen', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to earn', '0010', 'earns', 'earning', 'earned', 'earn'),
(1, 58, 'Facile', 'Put this verb in simple past : to take', '0100', 'tooken', 'took', 'toke', 'taken'),
(1, 58, 'Facile', 'Put this verb in simple past : to write', '0001', 'write', 'writed', 'written', 'wrote'),
(1, 58, 'Facile', 'Put this verb in simple past : to meet', '1000', 'met', 'meets', 'meeted', 'meeting'),
(1, 58, 'Facile', 'Put this verb in simple past : to copy', '010', 'copies', 'copied', 'copying', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to read', '0001', 'rough', 'rought', 'reads', 'read'),
(1, 58, 'Facile', 'Put this verb in simple past : to pay', '010', 'paied', 'paid', ' payed', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to say', '001', 'says', 'saying', 'said', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to do', '1000', 'did', 'does', 'doing', 'do'),
(1, 58, 'Facile', 'Put this verb in simple past : to need', '01', 'needs', 'needed', '', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to let', '01', 'letted', 'let', '', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to grow', '0001', 'grewed', 'growed', 'grow', 'grew'),
(1, 58, 'Facile', 'Put this verb in simple past : to choose', '0010', 'chosen', 'choosed', 'chose', 'choses'),
(1, 58, 'Facile', 'Put this verb in simple past : to answer', '010', 'answering', 'answered', 'answers', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to understand', '100', 'understood', 'understanded', 'understooded', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to jump', '001', 'jumps', 'jumping', 'jumped', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to memorize', '010', 'memorizing', 'memorized', 'memories', ''),
(1, 58, 'Facile', 'Put this verb in simple past : to break', '0010', 'breaks', 'breaked', 'broke', 'broken'),
(1, 58, 'Facile', 'Put this verb in simple present : to take', '001', 'I taked', 'I takes', 'I take', ''),
(1, 58, 'Facile', 'Put this verb in simple present : to sleep', '0001', 'I slept', 'I sleeps', 'I sleeping', 'I sleep'),
(1, 58, 'Facile', 'Put this verb in simple present : to fall', '010', 'I falls', 'I fall', 'I falled', ''),
(1, 58, 'Facile', 'Put this verb in simple present : to cry', '0100', 'I craught', 'I cry', 'I cries', 'I crying'),
(1, 58, 'Facile', 'Put this verb in simple present : to fail', '01', 'I failing', 'I fail', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', '');

/* Ajout Questions Forum */

INSERT INTO forumQuestion(question, id_student, answer)
VALUES('Question1', 1, ''),
('Question2', 1, ''),
('Question3', 1, ''),
('Question4', 1, ''),
('Question5', 1, ''),
('Question6', 1, ''),
('Question7', 1, ''),
('Question8', 1, ''),
('Question9', 1, ''),
('Question10', 1, ''),
('Question11', 1, ''),
('Question12', 1, ''),
('Question13', 1, '');

/* Ajout propositions questions forum */

INSERT INTO forumProposition(id_question, proposition)
VALUES(1, 'Proposition1'),
(1, 'Proposition2'),
(1, 'Proposition3'),
(1, 'Proposition4'),
(1, 'Proposition5'),
(2, 'Proposition1'),
(2, 'Proposition2'),
(2, 'Proposition3');