/*Destruction des tables*/

drop table if exists `admin`;
drop table if exists `professeur`;
drop table if exists `statistique`;
drop table if exists `etudiant`;
drop table if exists `questions`;
drop table if exists `sujets`;
drop table if exists `forumQuestion`;
drop table if exists `forumProposition`;

/* Création de la table utilisateur*/

create table `etudiant`(
	`id_etudiant` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_etudiant primary key (id_etudiant)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* Création de la table professeur */

create table `professeur`(
	`id_professeur` int not null auto_increment unique,
    `nom` varchar(30) not null,
    `prenom` varchar(50) not null,
    `email` varchar(50) unique not null,
    `telephone` varchar(10) unique not null,
    `password` varchar(512) not null,
    `adresse` varchar(60),
    constraint pk_professeur primary key (id_professeur)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Creation de la table administrateur*/

create table admin(
    id_admin varchar(20) unique,
    password varchar(512),
    constraint pk_admin primary key (id_admin)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

/* Création de la table statistique */

create table `statistique`(
    `id_statistique` int not null,
    `score` float,
    `id_subject` int not null
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


/*Creation de la table sujets */
create table sujets(
    id int auto_increment primary key,
    domaine varchar(50) not null,
    categorie varchar(50) not null,
    niveau varchar(50) not null
);

/*Creation de la table questions */

create table questions(
	id int auto_increment primary key,
    id_prof int not null,
    id_subject int not null,
    difficulte varchar(50) not null,
    question varchar(150) not null,
    code_reponses varchar(20) not null,
    reponseA varchar(150) not null,
    reponseB varchar(150) not null,
    reponseC varchar(150) not null,
    reponseD varchar(150) not null
);

/*Creation de la table forumQuestion */

create table forumQuestion(
    id int auto_increment primary key,
    question varchar(150) not null,
    id_student int not null,
    answer varchar(150)
);

/*Creation de la table forumProposition */

create table forumProposition(
    id_question int not null,
    proposition varchar(150) not null
);

/*Ajout Student*/
INSERT INTO etudiant(nom, prenom, email, telephone, password, adresse)
VALUES ('Student', 'Student', 'student@student.com', '0101010101', '2286db74888eee2de86d070c65fb9058486ac86e376f499da5fe90dae4d036fa026e7bbcb3a80f34adb7c38b2d3fe5153ed1dc302fd1776fe4b3bd0f9e4386f3', '1 rue des étudiants');

/*Ajout Prof*/
INSERT INTO professeur(nom, prenom, email, telephone, password, adresse)
VALUES ('Prof', 'Prof', 'prof@prof.com', '0202020202', 'b820e9862fa829c9af2ba64a64801097f4542590945b0ea539906e826950c5ba642a9b7d8a432b12f80aad8ad6428f6e7fe035d3e7f5ec5ce5564f5aa0d981ed', '1 rue des professeurs');

/*Ajout admin*/
INSERT INTO admin(id_admin, password)
VALUES ('admin', '5a38afb1a18d408e6cd367f9db91e2ab9bce834cdad3da24183cc174956c20ce35dd39c2bd36aae907111ae3d6ada353f7697a5f1a8fc567aae9e4ca41a9d19d');

/*Remplissage table sujets*/
INSERT INTO sujets(domaine, categorie, niveau)
values ('Mathematiques', 'Nombres', 'Primaire'),
('Mathematiques', 'Grandeurs', 'Primaire'),
('Mathematiques', 'Geometrie', 'Primaire'),
('Mathematiques', 'Statistiques', 'College'),
('Mathematiques', 'Geometrie', 'College'),
('Mathematiques', 'Algebre', 'College'),
('Mathematiques', 'Fonctions', 'Lycee'),
('Mathematiques', 'Suites', 'Lycee'),
('Mathematiques', 'Statistiques', 'Lycee'),
('Mathematiques', 'Algebre', 'Superieur'),
('Mathematiques', 'Analyse', 'Superieur'),
('Mathematiques', 'Probabilites', 'Superieur'),
('Physique', 'Electricite', 'College'),
('Physique', 'Lumiere', 'College'),
('Physique', 'Mecanique', 'College'),
('Physique', 'Electricite', 'Lycee'),
('Physique', 'Ondes', 'Lycee'),
('Physique', 'Optique', 'Lycee'),
('Physique', 'Mecanique', 'Lycee'),
('Physique', 'Mecanique', 'Superieur'),
('Physique', 'Electrocinetique', 'Superieur'),
('Physique', 'Thermodynamique', 'Superieur'),
('Chimie', 'Solutions aqueuses', 'College'),
('Chimie', 'Atomes', 'College'),
('Chimie', 'Atmosphere', 'College'),
('Chimie', '', 'Lycee'),
('Chimie', '', 'Superieur'),
('Biologie', '', 'College'),
('Biologie', '', 'Lycee'),
('Biologie', '', 'Superieur'),
('Geologie', '', 'College'),
('Geologie', '', 'Lycee'),
('Geologie', '', 'Superieur'),
('Informatique', '', 'College'),
('Informatique', 'Programmation', 'Lycee'),
('Informatique', '', 'Lycee'),
('Informatique', 'Programmation', 'Superieur'),
('Informatique', 'Reseaux', 'Superieur'),
('Informatique', 'S. d`exploitation', 'Superieur'),
('Histoire', 'Prehistoire', 'Primaire'),
('Histoire', 'Antiquite', 'Primaire'),
('Histoire', 'Moyen-Age', 'Primaire'),
('Histoire', 'Decouvertes', 'Primaire'),
('Histoire', '', 'Primaire'),
('Histoire', '', 'College'),
('Histoire', '', 'Lycee'),
('Histoire', '', 'Superieur'),
('Geographie', '', 'Primaire'),
('Geographie', '', 'College'),
('Geographie', '', 'Lycee'),
('Geographie', '', 'Superieur'),
('Francais', 'Conjugaison', 'Primaire'),
('Francais', '', 'Primaire'),
('Francais', '', 'College'),
('Francais', '', 'Lycee'),
('Francais', '', 'Superieur'),
('Anglais', '', 'Primaire'),
('Anglais', '', 'College'),
('Anglais', '', 'Lycee'),
('Anglais', '', 'Superieur');


/*Remplissage table questions*/

INSERT INTO questions (id_prof, id_subject, difficulte, question, code_reponses, reponseA, reponseB, reponseC, reponseD)
values (1, 1, 'Facile', '15 + 48 = ?', '010', '54', '63', '36', ''),
(1, 1, 'Facile', '48 - 15 = ?', '100', '23', '32', '33', ''),
(1, 1, 'Facile', '3 x 9 = ?', '001', '18', '36', '27', ''),
(1, 1, 'Facile', '45 / 9 = ?', '01', '4', '5', '', ''),
(1, 1, 'Facile', '15 + 450 = ?', '0100', '455', '465', '15450', '4515'),
(1, 1, 'Facile', '220 - 85 = ?', '1000', '135', '153', '165', '156'),
(1, 1, 'Facile', '7 x 3 = ?', '0010', '28', '14', '21', '35'),
(1, 1, 'Moyen', '56 / 8 = ?', '0001', '5', '6', '9', '7'),
(1, 1, 'Facile', '44 + ... = 78', '010', '25', '34', '38', ''),
(1, 1, 'Moyen', '890 - ... = 148', '001', '756', '648', '742', ''),
(1, 2, 'Facile', '16 cm = ?', '0011', '16 m', '1,6 m', '0,16 m', '160 mm'),
(1, 2, 'Facile', '42 km = ?', '0101', '420 m', '42000 m', '42 cm', '4200000 cm'),
(1, 2, 'Facile', '25 L = ?', '0100', '25 cL', '250 dL', '25000 cL', '2,5 hL'),
(1, 2, 'Facile', '30 mn = ?', '0010', '300 s', '1000 s', '1800 s', '180 s'),
(1, 2, 'Facile', 'Vrai ou Faux : 150 min = 2h30', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 300 ms = 3 s', '01', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 360 s = 6 mn', '10', 'Vrai', 'Faux', '', ''),
(1, 2, 'Facile', 'Vrai ou Faux : 4000 mL = 400 cL', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Facile', 'Comment se nomme une figure à 3 côtés ?', '010', 'Un cercle', 'Un triangle', 'Un carré', ''),
(1, 3, 'Facile', 'Comment appele-t-on la famille des figures à 4 côtés ?', '01', 'Les pentagones', 'Les quadrilatères', '', ''),
(1, 3, 'Facile', 'Quelle figure ne fait pas partie des quadrilatères ?', '0100', 'Le carré', 'Le pentagone', 'Le rectangle', 'Le losange'),
(1, 3, 'Moyen', 'Comment calculer le périmètre des carrés ?', '110', 'P = c * 4', 'P = (L + l) x 2', 'P = c x c', ''),
(1, 3, 'Moyen', 'Comment calculer le périmètre du cercle ?', '001', 'P = pi x r²', 'P = pi x r', 'P = pi x 2r', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle droit vaut 90°', '10', 'Vrai', 'Faux', '', ''),
(1, 3, 'Moyen', 'Vrai ou Faux : Un angle obtus est inférieur à 90°', '01', 'Vrai', 'Faux', '', ''),
(1, 4, 'Moyen', 'Quelle est la moyenne des nombres suivants : 12 18 ?', '0100', '14', '15', '16', '17'),
(1, 4, 'Facile', 'Quelle est la médiane des nombres : 13 15 18', '010', '16', '15', '15.33', ''),
(1, 4, 'Facile', 'Quelle est la moyenne des nombres : 7 15 20', '0010', '15', '16', '14', '17'),
(1, 4, 'Facile', 'Quel est le premier quartile ? : 5 10 15 14', '0100', '10', '5', '14', '15'),
(1, 4, 'Facile', '5 boules rouges et 2 boules noires. Probabilité de tirer une boule noire ?', '100', '2/7', '1/7', '5/7', ''),
(1, 4, 'Facile', '3 boules vertes, 2 boules bleues, 1 boule rouge. Probabilité de tirer 2 boules vertes ?', '0100', '2/6', '1/30', '1/11', '1/6'),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant à : 15/20', '010', '60%', '75%', '80%', ''),
(1, 4, 'Facile', 'Quel est le pourcentage correspondant à : 48/50', '01', '48%', '96%', '', ''),
(1, 4, 'Facile', 'Quelle est la fréquence correpondant à : 4 élèves sur 8', '010', '25%', '50%', '75%', ''),
(1, 4, 'Facile', 'Quelle est la fréquence correspondant à : 8 français sur 10', '0010', '8%', '40%', '80%', '90%'),
(1, 5, 'Facile', 'Quelle est l`hypothénuse d`un triangle rectangle', '01', 'Le côté le plus court', 'Le côté le plus long', '', ''),
(1, 5, 'Facile', 'Vrai ou Faux : On peut parler de la médiatrice d`une droite', '01', 'Vrai', 'Faux', '', ''),
(1, 5, 'Facile', 'Quelle est la définition de la bissectrice', '010', 'La droite perpendiculaire coupant un segment en deux parts égales', 'La droite coupant un angle en deux parts égales', 'La droite passant par le cente d`un segment', ''),
(1, 5, 'Facile', 'Comment calculer l`aire d`un carré ?', '001', 'A = 4 x c', 'A = c + c', 'A = c x c', ''),
(1, 5, 'Facile', 'Comment calculer le volume d`un parallélépipède rectangle', '010', 'V = l + L + h', 'V = l * L * h', 'V = l * L / h', ''),
(1, 5, 'Facile', 'Comment écrire "la droite AB"', '0100', '[AB]', '(AB)', '[AB)', '(AB]'),
(1, 5, 'Facile', 'Quel est le théorème de Pythagore ?', '0100', 'AB² = AC² = BC²', 'AB² + BC² = AC²', 'AB² - BC² = AC²', 'BC² + BA² = 2AC'),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle isocèle ?', '01', 'Un triangle a 3 côtés égaux', 'Un triangle à deux côtés égaux', '', ''),
(1, 5, 'Facile', 'Qu`est ce qu`un triangle rectangle', '0010', 'Un quadrilatère', 'Un triangle quelconque', 'Un triangle avec un angle droit', 'Un triangle à 3 côtés égaux'),
(1, 6, 'Facile', '3x + 15 = 12. x = ?', '0001', '-2', '2', '1', '-1'),
(1, 6, 'Facile', '12 - x = -2. x = ?', '0100', '10', '14', '16', '-10'),
(1, 6, 'Facile', '9x + 9 = 0. x = ?', '1000', '-1', '1', '10', '-10'),
(1, 6, 'Facile', '4x + 5 = x + 2. x = ?', '0010', '1', '3', '-1', '-3'),
(1, 6, 'Facile', '5x + 4 = 2x + 1. x = ?', '0100', '1', '-1', '3', '-3'),
(1, 6, 'Facile', '10x + 5 = 15x. x = ?', '0001', '10', '-1', '3', '1'),
(1, 7, 'Facile', 'Soit f(x) = 3x + 15. Que vaut f(5) ?', '0010', '60', '23', '30', '35'),
(1, 7, 'Facile', 'Soit f(x) = 14x + 12. Quelle est l`ordonnée à l`origine', '100', '12', '14', '26', ''),
(1, 7, 'Facile', 'Soit f(x) = x² + 2x + 1. Factoriser', '0100', 'x(x + 2) + 1', '(x + 1)²', '(x + 1)(x - 1)', '(x - 1)²'),
(1, 7, 'Facile', 'Soit f(x) = 4x² + 6x + 15. Dériver', '001', '4x + 6', '2x + 6', '8x + 6', ''),
(1, 7, 'Facile', 'Soit f(x) = 4x. Donner une primitive', '0001', 'x + constante', '4', '2x', '2x² + constante'),
(1, 7, 'Facile', 'Soit f(x) = 2x + 1. Sur quel intervalle est-elle positive ?', '0010', '[0; +inf[', '[1; +inf[', '[-1; +inf[', '[-1; +inf]'),
(1, 7, 'Facile', 'Soit f(x) = x². En quelle valeur s`annule-t-elle ?', '01', '1', '0', '', ''),
(1, 7, 'Facile', 'Soit f(x) = -x² + 3x. Sur quel intervalle est-elle croissante ?', '01', ']-inf; 1.5]', '[1.5; +inf[', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 4. u est-elle une suite géométrique ?', '01', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 4. u est-elle une suite géométrique ?', '10', 'Oui', 'Non', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_0 = 1 et u_n+1 = u_n * 4. Que vaut u_4 ?', '0010', '16', '8', '64', '128'),
(1, 8, 'Facile', 'Quelle est la suite arithmético-géométrique', '010', 'u_n+1 = u_n + a', 'u_n+1 = u_n * q + a', 'u_n+1 = u_n * q', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n + 16 et u_0 = 10. Quelle est la raison de u ?', '01', '10', '16', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+1 = u_n * 15 et u_0 = 12. Quelle est la raison de u ?', '10', '15', '12', '', ''),
(1, 8, 'Facile', 'Soit u telle que u_n+2 = u_n+1 + u_n, u_0 = 0 et u_1 = 1. Que vaut u_4 ?', '0100', '2', '3', '4', '5'),
(1, 8, 'Facile', 'Soit u telle que u_0 = 10 et u_n+1 = u_n. Que vaut u_100 ?', '0100', '10 000', '10', '1000', '1000'),
(1, 9, 'Facile', 'Quel est l`ensemble des résultats d`un dé non pipé ?', '0010', '{0, 1, 2, 3}', '{1, 3, 5}', '{1, 2, 3, 4, 5, 6}', '{2, 4, 6}'),
(1, 9, 'Facile', 'Soient A et B deux évènements. Que signifie A u B ?', '010', 'A inter B', 'A union B', 'A privé de B', ''),
(1, 9, 'Facile', 'Soient A et B deux évènements. Quelle est la probabilité conditionnelle ?', '0001', 'P(A u B)', 'P(A n B)', 'P(A \ B)', 'P_A(B)'),
(1, 9, 'Facile', 'Soient A et B deux évèenements. A n B signifie A inter B.', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Le cardinal d`un ensemble est le nombre d`éléments de cet ensemble', '10', 'Vrai', 'Faux', '', ''),
(1, 9, 'Facile', 'Soit A un évènement. Quelle est la probabilité de son évènement opposé ?', '1000', '1 - P(A)', 'P(A) - 1', '1 / P(A)', '-P(A)'),
(1, 9, 'Facile', 'On lance 10 fois un dé non pipé. Quelle loi utiliser pour cette étude ?', '01', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'On lance une fois un dé non pipé. Quelle loi utiliser pour cette étude ?', '10', 'Loi continue', 'Loi binomiale', '', ''),
(1, 9, 'Facile', 'Vrai ou Faux : Une variable aléaoire n`associe par toujours une issure à un réel', '01', 'Vrai', 'Faux', '', ''),
(1, 10, 'Facile', 'Que vaut cos(0) ?', '010', '0', '1', 'π', ''),
(1, 10, 'Facile', 'Quelle proposition est fausse ?', '0100', 'sin(−θ) = − sin(θ)', 'cos²(x) - sin²(x) = 1', 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)', 'sin(a + b) = sin(a)cos(b) + sin(b)cos(a)'),
(1, 10, 'Facile', 'Que vaut sin(π/6) ?', '01', '√3 / 2', '1 / 2', '', ''),
(1, 10, 'Facile', 'Quel est le théorème de Bézout ?', '01', 'Soient a, b, c, si a divise bc et PGCD(a;b) = 1, alors a divise c', 'Soient a, b; si PGCD(a,b)=1 alors il existe u,v tq au + bv = 1', '', ''),
(1, 10, 'Facile', 'Qu`est ce que la congruence entre deux nombres a et b ?', '010', 'Lorsqu`il existe q tel que a = bq', 'Lorsqu`il existe k tel que a - b = kn', 'Lorsqu`il existe (q, r) tel que a = bq + r', ''),
(1, 10, 'Facile', 'Comment s`écrit l`ensemble des racines n-ième de l`unité ?', '010', 'Q', 'U_n', 'UN', ''),
(1, 10, 'Facile', 'Quelle est la notation d`une racine n-ième de l`unité ?', '1000', 'exp(i * 2 * k * π / n) avec k dans [0, n - 1]', 'exp(iπ/n)', 'exp(ik/n) avec k dans [0, n - 1]', 'exp(i * k * π / n) avec k dans [0, n - 1]'),
(1, 10, 'Facile', 'Quelle est la notation exponentielle d`un nombre complexe ?', '0010', 'exp(i) = cos(iθ)', 'exp(θ) = cos(i) + sin(i)', 'exp(iθ) = cos(θ) + i*sin(θ)', 'exp(iθ) = cos(θ) - i*sin(θ)'),
(1, 10, 'Facile', 'Comment s`écrit un nombre complexe ?', '0011', 'z = i', 'z = xi', 'z = xi + y', 'z = xi - y'),
(1, 11, 'Facile', 'Vrai ou Faux : (g o f)` = g` x (f` o g)', '01', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Vrai ou Faux : (fg)`= f`g + fg`', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Soit f une fonction continue et strictement monotone sur I, alors : ', '001', 'f réalise une injection de I sur J = f(I)', 'f réalise une surjection de I sur J = f(I)', 'f réalise une bijection de I sur J = f(I)', ''),
(1, 11, 'Facile', 'Quand dit-on qu`une fonction f est continue en a ?', '0010', 'Lorsqu`elle est dérivable en a', 'Lorsque la limite en a est non nulle', 'Lorsque la limite en a vaut f(a)', 'Lorsque f s`annule en a'),
(1, 11, 'Facile', 'Si f(x) <= g(x) <= h(x) et si f et h admettent une limite l en a, alors g admet une limite l en a', '10', 'Vrai', 'Faux', '', ''),
(1, 11, 'Facile', 'Peut-il y avoir plusieurs limites pour une même valeur a ?', '01', 'Oui', 'Non', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en -inf de exp ?', '10', '0', '+inf', '', ''),
(1, 11, 'Facile', 'Quelle est la limite en 0 de ln ?', '0100', '0', '-inf', '+inf', 'e'),
(1, 11, 'Facile', 'Qu`est ce qu`une fonction dite CADLAG ?', '010', 'Cosinus à droite, Logarithme à gauche', 'Continue à droite, Limite à gauche', 'Croissante à droite, linéaire à gauche', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(A u B) = Card(A) + Card(B)', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Si A et B sont disjoints, Card(A u B) = Card(A) + Card(B)', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Card(E x F) = Card(E) x Card(F) où E et F sont deux ensembles', '10', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Vrai ou Faux : Une variable aléatoire réelle est une inconnue telle que x', '01', 'Vrai', 'Faux', '', ''),
(1, 12, 'Facile', 'Quand dit-on que deux évènements sont indépendants ?', '010', 'Lorsque P(A u B) = P(A)P(B)', 'Lorsque P(A n B) = P(A)P(B)', 'Lorsque P(A u B) = P(A) + P(B)', ''),
(1, 12, 'Facile', 'Quand dit-on que deux évènements sont incompatibles ?', '0100', 'Lorsque P(A n B) = A', 'Lorsque P(A u B) = P(A) + P(B)', 'Lorsque P(A u B) = P(A)', 'Lorsque P(A) = P(B)'),
(1, 12, 'Facile', 'Quelle est la formule de Pascal ?', '0001', 'nCp = (n-1)Cp', 'nCp = (n+1)C(p+1)', 'nC(p-1) = (p+1)C(n-1)', 'nCp = (n-1)Cp + (n-1)C(p-1)'),
(1, 13, 'Facile', 'Quelle loi s`applique pour l`intensité du courant dans un circuit en série ?', '01', 'La loi d`additivité', 'La loi d`unicité', '', ''),
(1, 13, 'Facile', 'Qu`est ce que la loi d`additivité d`intensité ?', '0100', 'L`intensité d`une branche dérivée est égale aux autres', 'L`intensité de la branche principale vaut la somme des dérivées', 'L`intensité d`une branche dérivée vaut la somme des autres', 'L`intensité est la même dans tout le circuit'),
(1, 13, 'Facile', 'Qu`est ce qu`un dipôle ?', '01', 'Un composant magnétique avec deux pôles', 'Un composant électrique avec deux bornes', '', ''),
(1, 13, 'Facile', 'Quand applique-t-on la loi d`additivité de la tension ?', '10', 'Un circuit en série', 'Un circuit en dérivation', '', ''),
(1, 13, 'Facile', 'Quelle est la loi d`Ohm ?', '0110', 'R = U x I', 'U = R x I', 'I = U / R', 'I = U x R'),
(1, 13, 'Facile', 'Comment mesure-t-on une intensité ?', '0001', 'Un voltmètre en dérivation', 'Un voltmètre en série', 'Un ampèremètre en dérivation', 'Un ampèremètre en série'),
(1, 13, 'Facile', 'Quelle est l`unité de l`intensité ?', '1000', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 13, 'Facile', 'Comment calcule-t-on la puissance électrique ?', '0010', 'P = U x R', 'P = U / I', 'P = U x I', 'U = P x I'),
(1, 13, 'Facile', 'Quelle est l`unité de la puissance électrique ?', '0001', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 13, 'Facile', 'Comment déterminer la valeur d`une résistance ?', '0110', 'En la branchant en série avec une intensité électrique prédéfinie', 'En regardant son code couleur', 'En utilisant un ohmmètre à l`extérieur du circuit', 'En utilisant un ohmmètre à l`intérieur du circuit'),
(1, 13, 'Facile', 'Quelle est l`unité de la tension ?', '0100', 'Ampère : A', 'Volt : V', 'Ohm : Ω', 'Watt : W'),
(1, 14, 'Facile', 'Sources de lumière : Quel est l`intrus ?', '001', 'Les sources primaires', 'Les objets diffusants', 'Les objets réflechissants', ''),
(1, 14, 'Facile', 'La trajectoire de la lumière est un mouvement ...', '0100', 'Circulaire', 'Rectiligne', 'Parabolique', 'Sinusoïdal'),
(1, 14, 'Facile', 'Quelles sont les couleurs qui composent la lumière ?', '0100', 'Rouge Bleu Jaune', 'Toutes les couleurs de Violet à Rouge', 'Rouge Vert Bleu', 'Magenta Jaune Cyan'),
(1, 14, 'Facile', 'A quoi est dûe la couleur d`un objet', '1100', 'Aux pigments présents sur l`objet', 'A la lumière éclairant l`objet', 'A la lumière que l`objet absorbe' , 'Au rayonnement naturel de l`objet'),
(1, 14, 'Facile', 'Quel comportement a la lumière avec une lentille convergente ?', '10', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quel comportement a la lumière avec une lentille divergente ?', '01', 'Les rayons lumineux convergent en un point', 'Les rayons lumineux divergent', '', ''),
(1, 14, 'Facile', 'Quelle est la vitesse de la lumière ?', '0010', '300 km/s', '3 000 m/s', '300 000 km/s', '300 000 m/s'),
(1, 14, 'Facile', 'Vrai ou Faux : Un oeil est comparable à une lentille avec un écran', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La lumière a la même vitesse quelque soit le milieu', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Magenta Jaune et Cyan sont les composantes principales de la lumière', '01', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : Utiliser deux couleurs de lumière permet d`en obtenir une autre', '10', 'Vrai', 'Faux', '', ''),
(1, 14, 'Facile', 'Vrai ou Faux : La vitesse de la lumière sert à mesurer des distances spatiales', '10', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Interactions : Quel est l`intrus ?', '001', 'L`interaction magnétique', 'L`interaction gravitationnelle', 'L`interaction mécanique', ''),
(1, 15, 'Facile', 'Qu`est ce que le poids d`un objet ?', '01', 'La quantité de matière d`un objet', 'L`action gravitationnelle exercée sur cet objet', '', ''),
(1, 15, 'Facile', 'Qu`est ce que la masse d`un objet ?', '10', 'La quantité de matière d`un objet', 'L`action gravitationnelle exercée sur cet objet', '', ''),
(1, 15, 'Facile', 'Quelle est la relation entre le poids et la masse ?', '0010', 'P = m / g', 'm = P x g', 'P = m x g', 'g = m x P'),
(1, 15, 'Facile', 'Qu`est ce que l`énergie ?', '010', 'Une quantité de mouvement', 'La capacité d`un objet à agir sur lui même et les autres', 'Une quantité de température', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie de position ?', '10', 'Une énergie dépendant de la hauteur', 'Une énergie dépendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie cinétique ?', '01', 'Une énergie dépendant de la hauteur', 'Une énergie dépendant de la vitesse', '', ''),
(1, 15, 'Facile', 'Qu`est ce que l`énergie mécanique ?', '01', 'Un terme général pour parler de l`énergie, cinétique ou de position', 'La comme de l`énergie cinétique et de l`énergie de position', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la formule de l`énergie cinétique est m x v²', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la masse n`influe pas sur l`énergie cinétique', '01', 'Vrai', 'Faux', '', ''),
(1, 15, 'Facile', 'Vrai ou Faux : la vitesse influe sur l`énergie cinétique', '10', 'Vrai', 'Faux', '', ''),
(1, 16, 'Facile', 'Qu`est ce qu`un noeud ?', '010', 'Un dipôle', 'Un point de connexion entre au moins 3 dipôles', 'Une partie de circuit', ''),
(1, 16, 'Facile', 'Qu`est ce qu`une maille  ?', '001', 'Un dipôle', 'Une partie de circuit', 'Une boucle fermée', ''),
(1, 16, 'Facile', 'Quelle est la loi des noeuds ?', '10', 'Somme des intensités entrantes = Somme des intensités sortantes', 'Somme des tensions entrantes = Somme des tensions sortantes', '', ''),
(1, 16, 'Facile', 'Quelle est la loi des mailles ?', '01', 'La somme des intensités dans une maille est nulle', 'La somme des tensions dans une maille est nulle', '', ''),
(1, 16, 'Facile', 'Comment représente t on la caractéristique d`un dipôle', '01', 'Un graphe Volt en x Ampère en y', 'Un graphe Ampère en x Volt en y', '', ''),
(1, 17, 'Facile', 'Qu`est ce qu`une onde mécanique ?', '0110', 'Un onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matière', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Qu`est ce qu`une onde électromagnétique', '1001', 'Une onde lumineuse', 'Une onde sonore', 'Une onde se propageant dans la matière', 'Une onde se propageant dans le vide'),
(1, 17, 'Facile', 'Quel est le symbôle de la fréquence d`une onde sonore', '01', 'f (fréquence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Quel est l`unité de la fréquence d`une onde sonore', '10', 'f (fréquence)', 'Hz (Hertz)', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : l`intensité sonore est exprimée en Watt', '01', 'Vrai', 'Faux', '', ''), 
(1, 17, 'Facile', 'Vrai ou Faux : une onde est doublement périodique', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Lors de la propagation d`une onde il y a déplacement de matière', '01', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Vrai ou Faux : Une onde est un transport d`énergie', '10', 'Vrai', 'Faux', '', ''),
(1, 17, 'Facile', 'Quand dit on qu`une onde mécanique est progressive', '010', 'Lorsqu`elle accélère progressivement', 'Lorsqu`elle se propage de proche en proche', 'Lorsqu`elle ralentit progressivement', ''),
(1, 17, 'Facile', 'Pour parler de la vitesse de propragation d`une onde on parle de ...', '01', 'Vitesse', 'Célérité', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 17, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 18, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 19, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 20, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 22, 'Facile', '', '01', '', '', '', ''),
(1, 21, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 23, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 24, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 25, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 26, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 27, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 28, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 30, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 29, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 31, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 32, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 33, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 34, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 35, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 37, 'Facile', '', '01', '', '', '', ''),
(1, 36, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 38, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 39, 'Facile', '', '01', '', '', '', ''),
(1, 40, 'Facile', 'Où ont été trouvés les plus vieux ossements humains ?', '1000', 'En Afrique', 'En Asie', 'En Europe', 'En Amérique'),
(1, 40, 'Facile', 'L`homme moderne est un', '10', 'Homo sapiens', 'Home neandertalis', '', ''),
(1, 41, 'Facile', 'L`écriture de l`Egypte antique se nomme', '10', 'Hiéroglyphe', 'Cursive', '', ''),
(1, 41, 'Facile', 'Cléopâtre régna sur l`Egypte vers', '1000', '40 avant Jésus-Christ', '400 avant Jésus-Christ', '40 après Jésus-Christ', '400 après Jésus-Christ'),
(1, 41, 'Facile', 'Vrai ou Faux : Vercingétorix était un soldat romain', '01', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Vrai ou Faux : Vercingétorix a déposé les armes à Alexia', '10', 'Vrai', 'Faux', '', ''),
(1, 41, 'Facile', 'Jules César est un personnage datant de', '1000', 'L`Antiquité', 'Le Moyen-âge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Clovis est né vers', '010', '1180', '466', '1980', ''),
(1, 42, 'Facile', 'Jeanne d`Arc est un personnage datant de', '0100', 'L`Antiquité', 'Le Moyen-âge', 'La Renaissance', 'Les Temps Modernes'),
(1, 42, 'Facile', 'Vrai ou Faux : Dagobert 1er régna avant Clovis', '01', 'Vrai', 'Faux', '', ''),
(1, 42, 'Facile', 'Quelle dynastie succéda à celle des Mérovingiens ?', '1000', 'Les Carolingiens', 'Les Capétiens', 'Les Valois', 'Les Bourbons'),
(1, 42, 'Facile', 'Charlemagne était le fils de ', '010', 'Clovis', 'Pépin le Bref', 'Hugues Capet', ''),
(1, 42, 'Facile', 'Sous quels autres noms connaît-on Louis IX', '110', 'Saint-Louis', 'Le Prudhomme', 'Louis le Bon', ''),
(1, 43, 'Facile', 'Quel élément n`est pas du Moyen-Âge ?', '001', 'Les châteaux forts', 'Les chevaliers', 'Les montgolfières', ''),
(1, 43, 'Facile', 'A qui doit-on l`invention de l`imprimerie ?', '0100', 'Léonard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'A qui doit-on l`invention de la machine à vapeur ?', '0010', 'Léonard de Vinci', 'Guttenberg', 'Papin', 'Einstein'),
(1, 43, 'Facile', 'Léonard de Vinci a travaillé pour ', '0100', 'Jules César', 'François 1er', 'Louis XIV', 'Napoléon'),
(1, 43, 'Facile', 'Parmi ces personnages qui étaient explorateurs ?', '1110', 'Marco Polo', 'Magellan', 'Christophe Collomb', 'Guttenberg'),
(1, 44, 'Facile', 'Louis XIV était surnommé', '10', 'Le roi Soleil', 'Le roi fainéant', '', ''),
(1, 44, 'Facile', 'Molière était ', '001', 'Chevalier', 'Roi', 'Ecrivain', ''),
(1, 44, 'Facile', 'La Révolution Française a eu lieu en ', '0100', '1515', '1789', '1804', '1968'),
(1, 44, 'Facile', 'La Bastille était ', '100', 'Une prison', 'La résidence du Roi', 'Une auberge', ''),
(1, 44, 'Facile', 'Quel roi fut guillotiné ?', '010', 'Henri IV', 'Louis XVI', 'Louis-Philippe', ''),
(1, 44, 'Facile', 'Napoléon Bonaparte devint empereur des Français en ', '001', '800', '1792', '1804', ''),
(1, 44, 'Facile', 'Le Général de Gaulle a combattu', '0001', 'Les Romains avec Vercingétorix', 'Les Anglais avec Jeanne d`Arc', 'Les Russes avec Napoléon', 'Les Allemands avec Churchill'),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 45, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 46, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 47, 'Facile', '', '01', '', '', '', ''),
(1, 48, 'Facile', 'Combien y a-t-il de continents ?', '001', '2', '4', '6', ''),
(1, 48, 'Facile', 'Quel fleuve n`est pas un fleuve Français ?', '0010', 'La Garonne', 'La Loire', 'Le Nil', 'La Seine'),
(1, 48, 'Facile', 'Quel est le plus long fleuve de France ?', '0001', 'La Garonne', 'Le Rhône', 'La Seine', 'La Loire'),
(1, 48, 'Facile', 'Quels massifs montagneux sont en France ?', '1110', 'Les Alpes', 'Les Pyrennées', 'Le Massif Central', 'L`Himalaya'),
(1, 48, 'Facile', 'Combien y a t-il de saisons en Europe ?', '10', '4', '2', '', ''),
(1, 48, 'Facile', 'En hiver, les nuits sont', '100', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Au printemps, les nuits sont', '010', 'plus longues que les jours', 'aussi longues que les jours', 'moins longues que les jours', ''),
(1, 48, 'Facile', 'Combien y a-t-il de jours dans une année ?', '100', '365-366 jours', '255-256 jours', '405-406 jours', ''),
(1, 48, 'Facile', 'Combien de jours comprend le mois de Mars ?', '001', '29', '30', '31', ''),
(1, 48, 'Facile', 'Une année de 366 jours s`appelle une année ...', '010', 'bipolaire', 'bissextile', 'bipode', ''),
(1, 48, 'Facile', 'Une année bissextile arrive tous les ', '1000', '4 ans', '5 ans', '6 ans', '7 ans'),
(1, 48, 'Facile', 'Vrai ou Faux : Le Soleil tourne autour de la Terre', '01', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Terre tourne sur elle-même', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'Vrai ou Faux : La Lune tourne autour de la Terre', '10', 'Vrai', 'Faux', '', ''),
(1, 48, 'Facile', 'La Lune tourne autour de la Terre en environ', '1000', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre tourne autour du Soleil en ', '0001', '1 mois', '3 mois', '6 mois', '1 an'),
(1, 48, 'Facile', 'La Terre fait un tour sur elle-même en ', '100', '1 jour', '1 mois', '1 an', ''),
(1, 48, 'Facile', 'Une journée dure ', '10', '24 heures', '12 heures', '', ''),
(1, 48, 'Facile', 'Le Soleil se lève', '1000', 'à l`Est', 'à l`Ouest', 'au Nord', 'au Sud'),
(1, 48, 'Facile', 'Comment appelle-t-on Nord, Est, Ouest, Sud', '001', 'Les points noirs', 'Les points blancs', 'Les points cardinaux', ''),
(1, 48, 'Facile', 'Quelles mers bordent la France ?', '101', 'Mer méditerrannée', 'Mer rouge', 'La Manche', ''),
(1, 48, 'Facile', 'A combien culmine le Mont Blanc ?', '100', '4807', '8848', '5891', ''),
(1, 48, 'Facile', 'Quels pays ont frontière commune avec la France ?', '110', 'La Belgique', 'L`Allemagne', 'La Russie', ''),
(1, 48, 'Facile', 'Quelle la capitale de la France ?', '100', 'Paris', 'Lille', 'Marseille', ''),
(1, 48, 'Facile', 'Combien de pays comprend l`union européenne ?', '010', '17', '27', '37', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 49, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 50, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 51, 'Facile', '', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 1er groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 2ème groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ème groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Quels verbes sont du 3ème groupe ?', '01', '', '', '', ''),
(1, 52, 'Facile', 'Présent  : Vous (manger)', '01', '', '', '', ''),
(1, 52, 'Facile', 'Futur : Vous (courir)', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', 'Imparfait : Ils (finir)', '', '', ''),
(1, 53, 'Facile', '', '01', 'Passé Composé : Tu (aller)', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : On entend le rossignol chanter', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : La fusée décollera à 12 heures', '', '', ''),
(1, 53, 'Facile', '', '01', 'Quel temps : Nous étions les rois du monde', '', '', ''),
(1, 53, 'Facile', '', '01', 'Où est le verbe : Le chat mange une souris', '', '', ''),
(1, 53, 'Facile', '', '01', 'Qui est le nom noyau : La petite fille aux alumettes', '', '', ''),
(1, 53, 'Facile', '', '01', 'Combien de verbes : Le chat suit des yeux le mulot, se tapit, puis bondit dessus', '', '', ''),
(1, 53, 'Facile', '', '01', 'COD ou COI (une souris) : Le chat mange une souris', '', '', ''),
(1, 53, 'Facile', '', '01', 'COD ou COI (à sa grand-mère) : La fille écrit à sa grand-mère', '', '', ''),
(1, 53, 'Facile', '', '01', 'Nature de "Sous le rebord de la fenêt', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 53, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 54, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 55, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 56, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 57, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 58, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 59, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', ''),
(1, 60, 'Facile', '', '01', '', '', '', '');

